Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2018-09, with the labels that each got.

#14 Update the CNI to weave
  cloud/vsphere/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#37 Add the types for the provider status fields
  cloud/vsphere/vsphereproviderconfig/register.go
  cloud/vsphere/vsphereproviderconfig/types.go
  cloud/vsphere/vsphereproviderconfig/v1alpha1/register.go
  cloud/vsphere/vsphereproviderconfig/v1alpha1/types.go
  cloud/vsphere/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/vsphere/vsphereproviderconfig/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#42 Add vsphere cluster controller
  Gopkg.lock
  cloud/vsphere/clusteractuator.go
  cloud/vsphere/cmd/vsphere-machine-controller/main.go
  cloud/vsphere/instancestatus.go
  cloud/vsphere/machineactuator.go
  cloud/vsphere/utils.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/actuator.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/queue.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/testactuator.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/zz_generated.api.register.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#50 Updated refactor actuator
  Gopkg.lock
  cloud/vsphere/clusteractuator.go
  cloud/vsphere/constants/constants.go
  cloud/vsphere/deployer.go
  cloud/vsphere/machineactuator.go
  cloud/vsphere/provisioner/commands.go
  cloud/vsphere/provisioner/govmomi/create.go
  cloud/vsphere/provisioner/govmomi/delete.go
  cloud/vsphere/provisioner/terraform/templates.go
  cloud/vsphere/provisioner/terraform/terraform.go
  cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#58 Refactor template.go out of terraform to be used as common code
  cloud/vsphere/provisioner/common/templates.go
  cloud/vsphere/provisioner/terraform/terraform.go
  cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#59 Add how to instructions for clusterctl
  README.md
  docs/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L
