Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2018-12, with the labels that each got.

#137 clusterapi vsphere e2e test
  scripts/e2e/README.md
  scripts/e2e/bootstrap_job.yml
  scripts/e2e/bootstrap_job/Dockerfile
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/bootstrap_job/spec/cluster.template
  scripts/e2e/bootstrap_job/spec/machines.template
  scripts/e2e/bootstrap_job/spec/machineset.template
  scripts/e2e/bootstrap_job/spec/provider-components-v1.0.template
  scripts/e2e/bootstrap_job/spec/provider-components-v2.0.template
  scripts/e2e/bootstrap_secret.template
  scripts/e2e/e2e.sh
  scripts/e2e/hack/Dockerfile
  scripts/e2e/hack/Makefile
  scripts/e2e/hack/job.yml
  scripts/e2e/hack/secret.yml
  scripts/e2e/wait_for_job.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#142 Fix .gitignore for OVA
  installer/.gitignore
  installer/build/bootable/root/opt/ova/bin/kubeadm-provisioning.sh
  installer/build/bootable/root/opt/ova/bin/kubernetes-watchdog.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#143 compile clusterctl for every e2e ci job
  Makefile
  cmd/clusterctl/Dockerfile
  scripts/e2e/bootstrap_job.template
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#147 Add Build and Deploy docs for OVA
  docs/ova/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#150 Added option to generate.sh to use custom kubecon 2018 containers
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#148 Fix kubeadm token
  Gopkg.lock
  Gopkg.toml
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  pkg/cloud/vsphere/provisioner/govmomi/utils.go
  vendor/k8s.io/cluster-bootstrap/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/cluster-bootstrap/CONTRIBUTING.md
  vendor/k8s.io/cluster-bootstrap/Godeps/Godeps.json
  vendor/k8s.io/cluster-bootstrap/Godeps/OWNERS
  vendor/k8s.io/cluster-bootstrap/Godeps/Readme
  vendor/k8s.io/cluster-bootstrap/LICENSE
  vendor/k8s.io/cluster-bootstrap/OWNERS
  vendor/k8s.io/cluster-bootstrap/README.md
  vendor/k8s.io/cluster-bootstrap/SECURITY_CONTACTS
  vendor/k8s.io/cluster-bootstrap/code-of-conduct.md
  vendor/k8s.io/cluster-bootstrap/token/OWNERS
  vendor/k8s.io/cluster-bootstrap/token/api/doc.go
  vendor/k8s.io/cluster-bootstrap/token/api/types.go
  vendor/k8s.io/cluster-bootstrap/token/util/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#151 Add CI parameters to OVA build
  docs/ova/README.md
  installer/build/bootable/build-main.sh
  installer/build/bootable/config/builder.ovf
  installer/build/build-ova.sh
  installer/build/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#152 e2e ci improvement
  scripts/e2e/README.md
  scripts/e2e/bootstrap_job.template
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/bootstrap_job/spec/machines.template
  scripts/e2e/bootstrap_secret.template
  scripts/e2e/e2e.sh
  scripts/e2e/hack/Dockerfile
  scripts/e2e/hack/Makefile
  scripts/e2e/hack/job.yml
  scripts/e2e/hack/secret.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#156 Removed travis ci config file
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#162 Update quickstart guide and add demo links
  docs/README.md
  docs/self-service/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
