Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2018-11, with the labels that each got.

#110 Overload the VMTemplate parameter for search purposes
  Gopkg.lock
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#115 Misc fixes
  Gopkg.lock
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/update.go
  pkg/cloud/vsphere/utils/utils.go
  vendor/github.com/cenkalti/backoff/LICENSE
  vendor/github.com/cenkalti/backoff/backoff.go
  vendor/github.com/cenkalti/backoff/context.go
  vendor/github.com/cenkalti/backoff/exponential.go
  vendor/github.com/cenkalti/backoff/retry.go
  vendor/github.com/cenkalti/backoff/ticker.go
  vendor/github.com/cenkalti/backoff/tries.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#116 Add labels to the nodes created via Machines
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#117 Add the namespace to the "machine" annotation on the Node
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#124 Make the install and configure part of the scripts match the intent
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#127 Update quickstart
  docs/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#129 Add sflxn as maintainer.
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Update quickstart guide for post-crd
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  docs/quickstart.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#126 Remove terraform actuators
  Dockerfile
  Gopkg.lock
  cmd/clusterctl/examples/vsphere/README.md
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  cmd/clusterctl/examples/vsphere/namedmachines.yaml.template
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  pkg/apis/vsphereproviderconfig/types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types_test.go
  pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/vsphereproviderconfig/zz_generated.deepcopy.go
  pkg/cloud/vsphere/machineactuator.go
  pkg/cloud/vsphere/provisioner/terraform/terraform.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#130 Clean up the code post terraform provider removal
  Dockerfile
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  docs/quickstart.md
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types_test.go
  pkg/cloud/vsphere/constants/constants.go
  pkg/cloud/vsphere/namedmachines/namedmachines.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#131 Add a few more dependencies to the CI build target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#133 Add test for govmomi actuator Create method
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/create_test.go
  pkg/cloud/vsphere/provisioner/govmomi/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#136 fix the error message
  pkg/controller/add_machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
