Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2018-10, with the labels that each got.

#65 Bring vendor dir in sync
  .gitignore
  Gopkg.lock
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/github.com/vmware/govmomi/simulator/license_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#68 Fix the kubelet config for version 1.11 and above
  cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#69 run dep ensure when run make test
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#75 Use release version dep tool
  Makefile
  cloud/vsphere/provisioner/terraform/terraform.go
  cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#77 Fix govmomi actuator's Create when using clusterctl
  cloud/vsphere/clusteractuator.go
  cloud/vsphere/machineactuator.go
  cloud/vsphere/provisioner/govmomi/create.go
  cloud/vsphere/provisioner/govmomi/exists.go
  cloud/vsphere/provisioner/govmomi/provisioner.go
  cloud/vsphere/provisioner/govmomi/update.go
  cloud/vsphere/provisioner/govmomi/utils.go
  cloud/vsphere/utils/utils.go
  cloud/vsphere/vsphereproviderconfig/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#84 Update the Makefile to reflect the new folder structure
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#80 Promote vsphereproviderconfig api to root folder
  Makefile
  pkg/apis/vsphereproviderconfig/doc.go
  pkg/apis/vsphereproviderconfig/register.go
  pkg/apis/vsphereproviderconfig/types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/doc.go
  pkg/apis/vsphereproviderconfig/v1alpha1/register.go
  pkg/apis/vsphereproviderconfig/v1alpha1/types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/vsphereproviderconfig/zz_generated.deepcopy.go
  pkg/cloud/vsphere/clusteractuator.go
  pkg/cloud/vsphere/constants/constants.go
  pkg/cloud/vsphere/machineactuator.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/update.go
  pkg/cloud/vsphere/provisioner/terraform/terraform.go
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Add a new MachineSpec for defining the instance on vsphere
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  pkg/apis/vsphereproviderconfig/types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/types.go
  pkg/cloud/vsphere/clusteractuator.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/exists.go
  pkg/cloud/vsphere/provisioner/govmomi/update.go
  pkg/cloud/vsphere/provisioner/terraform/terraform.go
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 Use enhanced MachineSpec to provision
  pkg/cloud/vsphere/provisioner/common/templates.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#98 add e2e CI into repo
  .travis.yml
  Makefile
  cmd/vsphere-machine-controller/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#92 Add goflag parsing to pflags
  cmd/vsphere-machine-controller/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#101 add vmFolder in machineSpec
  .travis.yml
  pkg/apis/vsphereproviderconfig/types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/vsphereproviderconfig/zz_generated.deepcopy.go
  pkg/cloud/vsphere/constants/constants.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/L
