Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-09, with the labels that each got.

#540 Updates to bring CAPV v1alpha2 to working status
  .gitignore
  Makefile
  api/v1alpha2/vspherecluster_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/rbac/role.yaml
  controllers/vspherecluster_controller.go
  controllers/vspheremachine_controller.go
  docs/design/cloud-init-networking.puml
  docs/getting_started.md
  examples/addons.yaml
  examples/cluster/cluster.yaml
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
  examples/provider-components/cabpk_image_patch.yaml
  examples/provider-components/cabpk_manager_patches.yaml
  examples/provider-components/capi_manager_patches.yaml
  examples/provider-components/capv_manager_patches.yaml
  examples/provider-components/kustomization.yaml
  hack/build-dev.sh
  pkg/cloud/vsphere/services/govmomi/extra/config.go
  pkg/cloud/vsphere/services/govmomi/service.go
  pkg/cloud/vsphere/util/machines.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#542 Add missing cloud provider config
  examples/controlplane/controlplane.yaml
  examples/generate.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#544 Update getting started doc with release images
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 switching from kubeadm module to runcmd in cloud-init userdata
  pkg/cloud/vsphere/services/userdata/controlplane.go
  pkg/cloud/vsphere/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#547 Add -b option to hack/release.sh
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#545 Selectable CRI socket
  pkg/cloud/vsphere/services/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#550 use Join NodeRegistration for CRI socket path on kubeadm join
  pkg/cloud/vsphere/services/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#553 remove MachineRef when vm is deleted
  pkg/cloud/vsphere/services/govmomi/service.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#546 Update generation script w correct CABPK image
  examples/generate.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#556 add label to be able to list vspheremachines that are part of cluster
  examples/controlplane/controlplane.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#559 Add service domain to the cluster config
  docs/getting_started.md
  examples/cluster/cluster.yaml
  examples/generate.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#564 git ignore envars.txt
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#563 fix e2e: broken link to download clusterctl
  scripts/e2e/bootstrap_job.template
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/e2e.sh
  scripts/e2e/generate-e2e-spec.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#566 use govmomi types.VirtualEthernetCardMacType for NIC address type
  pkg/cloud/vsphere/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#567 Add the vendor directory to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#569 Add staticchecking script and makefile target
  Makefile
  controllers/vspheremachine_annotations.go
  go.mod
  go.sum
  hack/check-staticcheck.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#573 add service domain to the sample work-cluster manifest
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#574 The default version changed to 1.14.4 but docs does not change
  docs/getting_started.md
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#579 update calico addons to use apps/v1 instead of extensions/v1beta1
  examples/default/addons.yaml
  examples/pre-67u3/addons.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#580 add missing deployment selectors in calico addon
  examples/default/addons.yaml
  examples/pre-67u3/addons.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#571 Remove hack/verify-install.sh
  Makefile
  hack/verify-install.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#578 Support vSphere CSI for vSphere >= 6.7u3
  api/v1alpha2/cloudprovider/doc.go
  api/v1alpha2/cloudprovider/encoding.go
  api/v1alpha2/cloudprovider/encoding_test.go
  api/v1alpha2/cloudprovider/types.go
  api/v1alpha2/cloudprovider/zz_generated.deepcopy.go
  api/v1alpha2/vspherecluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  controllers/vspherecluster_controller.go
  docs/getting_started.md
  examples/default/cluster/cluster.yaml
  pkg/cloud/vsphere/services/cloudprovider/cloud-controller-manager.go
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#590 Allow user to set kubeadm clusterConfiguration imageRepository
  examples/default/controlplane/controlplane.yaml
  examples/generate.sh
  examples/pre-67u3/controlplane/controlplane.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#592 Go module dependency updates
  examples/generate.sh
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#593 Fix cloudprovider encoding tests
  api/v1alpha2/cloudprovider/encoding.go
  api/v1alpha2/cloudprovider/encoding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#594 support cluster-id in cloud config which is required by vSphere CSI driver
  api/v1alpha2/cloudprovider/encoding_test.go
  api/v1alpha2/cloudprovider/types.go
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#595 vSphere CSI daemonset and statefulset should use non-conflicting health ports for liveness
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#596 fix null field in SSH authorized keys due to kustomize removing double quotes
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#597 single quote resource pool in manifest generation since it can begin with special characters like *
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
