Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-01, with the labels that each got.

#170 Fix quickstart link
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#172 Remove docker.sock mount from OVA build script
  installer/build/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 Remove redundancies in the kustomize files
  config/default/kustomization.yaml
  config/default/vsphere_manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 Add support to inject custom trusted certs into the machines
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  docs/design/trustedCerts.md
  docs/self-service/README.md
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/vsphere/provisioner/common/templates.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/M
