Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-08, with the labels that each got.

#476 Bugfix: Double base64 encoding of cloud provider credentials
  pkg/cloud/vsphere/actuators/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#470 Do not error on multiple network devices if at least one has a valid IP address
  pkg/cloud/vsphere/context/cluster_context.go
  pkg/cloud/vsphere/context/machine_context.go
  pkg/cloud/vsphere/context/machine_context_test.go
  pkg/cloud/vsphere/services/govmomi/update.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#478 Fix indentation for increasing log level
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#482 Remove E2E use of hardcoded path to key file
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#457 generate e2e spec files at runtime
  scripts/e2e/bootstrap_job.template
  scripts/e2e/bootstrap_job/Dockerfile
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/bootstrap_job/spec/cluster.template
  scripts/e2e/bootstrap_job/spec/machines.template
  scripts/e2e/bootstrap_job/spec/machineset.template
  scripts/e2e/bootstrap_job/spec/provider-components.template
  scripts/e2e/bootstrap_secret.template
  scripts/e2e/e2e.sh
  scripts/e2e/generate-e2e-spec.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#484 moved preferredAPIServerCidr in troubleshooting doc to correct line
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#489 docs: remove controlPlane version field for worker…
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#493 CAPI 0.1.9
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/config/default/kustomization.yaml
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/machine_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#471 Centralized cloud provider configuration
  cmd/clusterctl/examples/vsphere/cluster.yaml.template
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  config/crds/vsphere_v1alpha1_vsphereclusterproviderspec.yaml
  config/crds/vsphere_v1alpha1_vspheremachineproviderspec.yaml
  docs/getting_started.md
  go.mod
  go.sum
  hack/generate-yaml.sh
  hack/update-generated.sh
  pkg/apis/vsphere/v1alpha1/cloud/doc.go
  pkg/apis/vsphere/v1alpha1/cloud/encoding.go
  pkg/apis/vsphere/v1alpha1/cloud/encoding_test.go
  pkg/apis/vsphere/v1alpha1/cloud/types.go
  pkg/apis/vsphere/v1alpha1/cloud/zz_generated.deepcopy.go
  pkg/apis/vsphere/v1alpha1/vsphereclusterproviderspec_types.go
  pkg/apis/vsphere/v1alpha1/vspheremachineproviderspec_types.go
  pkg/apis/vsphere/v1alpha1/vspheremachineproviderspec_types_test.go
  pkg/apis/vsphere/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/vsphere/actuators/cluster/actuator.go
  pkg/cloud/vsphere/services/govmomi/create.go
  pkg/cloud/vsphere/services/govmomi/create_test.go
  pkg/cloud/vsphere/services/govmomi/vcenter/clone.go
  pkg/cloud/vsphere/services/userdata/controlplane.go
  pkg/cloud/vsphere/services/userdata/controlplane_test.go
  vendor/golang.org/x/tools/go/internal/cgo/cgo.go
  vendor/golang.org/x/tools/go/internal/cgo/cgo_pkgconfig.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_fallback.go
  vendor/golang.org/x/tools/go/packages/golist_fallback_testmain.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/mod.go
  vendor/gopkg.in/gcfg.v1/LICENSE
  vendor/gopkg.in/gcfg.v1/README
  vendor/gopkg.in/gcfg.v1/doc.go
  vendor/gopkg.in/gcfg.v1/errors.go
  vendor/gopkg.in/gcfg.v1/read.go
  vendor/gopkg.in/gcfg.v1/scanner/errors.go
  vendor/gopkg.in/gcfg.v1/scanner/scanner.go
  vendor/gopkg.in/gcfg.v1/set.go
  vendor/gopkg.in/gcfg.v1/token/position.go
  vendor/gopkg.in/gcfg.v1/token/serialize.go
  vendor/gopkg.in/gcfg.v1/token/token.go
  vendor/gopkg.in/gcfg.v1/types/bool.go
  vendor/gopkg.in/gcfg.v1/types/doc.go
  vendor/gopkg.in/gcfg.v1/types/enum.go
  vendor/gopkg.in/gcfg.v1/types/int.go
  vendor/gopkg.in/gcfg.v1/types/scan.go
  vendor/gopkg.in/warnings.v0/LICENSE
  vendor/gopkg.in/warnings.v0/README
  vendor/gopkg.in/warnings.v0/warnings.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#474 setting hostname of machines using cloud-init
  pkg/cloud/vsphere/services/userdata/controlplane.go
  pkg/cloud/vsphere/services/userdata/node.go
  pkg/cloud/vsphere/services/userdata/userdata.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#504 allow for time skew in cert generation
  pkg/cloud/vsphere/services/certificates/certificates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#509 fix a few typos found when reading around
  docs/getting_started.md
  pkg/cloud/vsphere/services/govmomi/template/template.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#518 Fixing a misspelled word
  api/v1alpha2/cloud/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#519 Remove vestigial documentation
  docs/design/machine-actuator-create-workflow.puml
  docs/design/machine-actuator-create-workflow.svg
  docs/design/machine-actuator-exists-workflow.puml
  docs/design/machine-actuator-exists-workflow.svg
  docs/design/ntpServers.md
  docs/design/trustedCerts.md
  docs/machine_images.md
  docs/ova/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#532 Update getting started guide with info about v1a2'isms
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#534 fix to manifests generation
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#533 Manifests generation update
  examples/controlplane/controlplane.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#539 rbac fixes
  api/v1alpha2/vspherecluster_types.go
  api/v1alpha2/vspheremachine_types.go
  api/v1alpha2/vspheremachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/rbac/role.yaml
  controllers/vspherecluster_controller.go
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M
