Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-03, with the labels that each got.

#206 Putting resources used by kustomization.yaml into its sub-folder
  .gitignore
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  config/crds/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/rbac/kustomization.yaml
  docs/self-service/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#210 Unify machine spec of machine.yaml and machinset.yaml
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#218 Prevent nil providerSpec from panicking
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#226 Resolved an annotation name changed
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#213 Fix cloning from template with snapshot and simultaneous disk expansion
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#221 Set the cache resync period to 2 min
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 Use the machine's ID as the instance UUID of the VM
  docs/design/create-workflow.png
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#231 Pin docker to version 18.06 to ensure kubeadm's compatibility
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#227 Enable the latest Kustomize version check
  Makefile
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#233 Add nil check for the cluster ProviderStatus
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#234 Update docs with information on creating a custom cloud init
  docs/self-service/README.md
  docs/self-service/cloud_init_with_guestinfo_datasource.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/S

#240 Fix bootstrap script to fix kubernetes-cni issue in k8s 1.14
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#241 Use a better shell command to grab the IP address
  pkg/cloud/vsphere/provisioner/common/templates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#243 Add version compatibility matrix against CAPI and k8s
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
