Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-12, with the labels that each got.

#678 Document the API endpoint discovery process
  docs/design/api-endpoint-discovery.puml
  docs/design/api-endpoint-discovery.svg
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#679 Fixes error when using -P flag with generator
  examples/generate.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#681 restore machine deletion
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#686 Reconcile based on task completion
  .golangci.yml
  controllers/vspherecluster_controller.go
  controllers/vspheremachine_controller.go
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/context/controller_manager_context.go
  pkg/manager/manager.go
  pkg/services/govmomi/context.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
  pkg/util/machines.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#688 Update OVA links in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#689 add v1alpha3 API types
  PROJECT
  api/v1alpha3/cloudprovider/doc.go
  api/v1alpha3/cloudprovider/encoding.go
  api/v1alpha3/cloudprovider/encoding_test.go
  api/v1alpha3/cloudprovider/types.go
  api/v1alpha3/cloudprovider/zz_generated.deepcopy.go
  api/v1alpha3/doc.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/types.go
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/vspheremachine_types.go
  api/v1alpha3/vspheremachinetemplate_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#690 Update manifest base image & manifest image
  hack/tools/generate-yaml/Dockerfile
  hack/tools/manifests-base/Dockerfile
  hack/tools/manifests-base/Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#685 Move capv to v1alpha3
  api/v1alpha3/types.go
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  controllers/vspherecluster_controller.go
  controllers/vspheremachine_controller.go
  examples/default/cluster/cluster.yaml
  examples/default/cluster/kustomizeconfig.yaml
  examples/default/controlplane/controlplane.yaml
  examples/default/controlplane/kustomizeconfig.yaml
  examples/default/machinedeployment/kustomizeconfig.yaml
  examples/default/machinedeployment/machinedeployment.yaml
  examples/default/provider-components/cabpk_manager_patches.yaml
  examples/default/provider-components/kustomization.yaml
  examples/default/provider-components/manager_tolerations_patch.yaml
  examples/generate.sh
  examples/pre-67u3/cluster/cluster.yaml
  examples/pre-67u3/cluster/kustomizeconfig.yaml
  examples/pre-67u3/controlplane/controlplane.yaml
  examples/pre-67u3/controlplane/kustomizeconfig.yaml
  examples/pre-67u3/machinedeployment/kustomizeconfig.yaml
  examples/pre-67u3/machinedeployment/machinedeployment.yaml
  go.mod
  go.sum
  hack/build-dev.sh
  main.go
  pkg/constants/constants.go
  pkg/context/cluster_context.go
  pkg/context/fake/constants.go
  pkg/context/fake/fake_cluster_context.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/context/fake/fake_machine_context.go
  pkg/context/machine_context.go
  pkg/manager/manager.go
  pkg/manager/options.go
  pkg/services/cloudprovider/cloud-controller-manager.go
  pkg/services/cloudprovider/csi.go
  pkg/services/govmomi/context.go
  pkg/services/govmomi/service.go
  pkg/services/interfaces.go
  pkg/session/session.go
  pkg/util/kubeadm.go
  pkg/util/kubeadm_test.go
  pkg/util/kubeclient.go
  pkg/util/machines.go
  pkg/util/machines_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#693 use equate-empty in comparing machine status
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#694 Add warning to getting started guide to carefully handle the .ova suffix
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#698 Support a control plane endpoint annotation for v1a2
  api/v1alpha2/types.go
  controllers/vspherecluster_controller.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#700 vSphere cloud provider 1.1.0
  docs/getting_started.md
  examples/default/cluster/cluster.yaml
  pkg/services/cloudprovider/cloud-controller-manager.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#701 Cluster API 0.2.8
  examples/generate.sh
  go.mod
  go.sum
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#702 Update getting started doc to use release-0.5
  docs/getting_started.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#707 Set network interface name with cloud-init set-name
  api/v1alpha2/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  docs/troubleshooting.md
  pkg/util/constants.go
  pkg/util/machines_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M
