Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-06, with the labels that each got.

#264 Standalone esx
  Dockerfile
  cmd/clusterctl/Dockerfile
  config/rbac/rbac_role.yaml
  docs/self-service/README.md
  docs/self-service/esx_provisioning.md
  pkg/cloud/vsphere/provisioner/common/esx/scripts.go
  pkg/cloud/vsphere/provisioner/common/templates.go
  pkg/cloud/vsphere/provisioner/common/vc/scripts.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/create_test.go
  pkg/cloud/vsphere/provisioner/govmomi/session.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#266 fix a small typo in deployment instructions
  docs/ova/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#278 Add troubleshooting Information to Self-Service Docs
  docs/self-service/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#287 restore e2e test cleanup
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#291 Get control plane machines by cluster name
  pkg/cloud/vsphere/clusteractuator.go
  pkg/cloud/vsphere/provisioner/govmomi/utils.go
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#293 fix master -> control plane
  pkg/cloud/vsphere/clusteractuator.go
  pkg/cloud/vsphere/provisioner/govmomi/utils.go
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#281 Add akutz and andrewsykim to OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#295 remove the default weave CNI
  cmd/clusterctl/examples/vsphere/addons.yaml.template
  cmd/clusterctl/examples/vsphere/cluster.yaml.template
  pkg/cloud/vsphere/provisioner/common/vc/scripts.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#296 Use calico CNI for the example initial target cluster
  cmd/clusterctl/examples/vsphere/addons.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XL

#297 Add addons.yaml into ci deployment
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/bootstrap_job/clusterctl.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#279 Update CRDs
  config/crds/vsphereproviderconfig_v1alpha1_vsphereclusterproviderconfig.yaml
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  go.mod
  go.sum
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/bootstrap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/certgenerator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/selfsigned.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/generator/util.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/provisioner.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/atomic/atomic_writer.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/certwriter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/error.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/fs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/cert/writer/secret.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/util.go
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/generate/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/index.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/util.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/types.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/general/util.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/manifests.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/client.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/internal/manager.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/manifests.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#280 Validate that CRDs are generated prior to commit
  .gitignore
  Makefile
  config/crds/.gitignore
  config/crds/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#298 Enable custom boot timeout, VNC, & packer flags
  build/images/Makefile
  build/images/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#299 Shell with GOPATH
  .gitignore
  Makefile
  config/crds/.gitignore
  config/crds/Makefile
  hack/shell-with-gopath.sh
  hack/update-generated.sh
  hack/verify-crds.sh
  pkg/apis/apis.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#283 Install kustomize v2 if missing
  .gitignore
  Makefile
  hack/ensure-tools.sh
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#300 Use envsubst for clusterctl yaml generation
  .gitignore
  Makefile
  cmd/clusterctl/examples/vsphere/cluster.yaml.template
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  cmd/clusterctl/examples/vsphere/vsphere_manager_image_patch.yaml.template
  config/default/.gitignore
  hack/ensure-tools.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#302 Add better install instructions for envsubst
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  hack/ensure-tools.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#303 Fix base64 bug in hack/image-post-create-config.sh
  hack/image-post-create-config.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#305 clusterctl: templatize more env vars for clusterctl yaml generation
  Makefile
  cmd/clusterctl/examples/vsphere/capv_manager_image_patch.yaml.template
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  config/default/.gitignore
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#309 Use envsubst for template file
  scripts/e2e/bootstrap_job/Dockerfile
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/bootstrap_job/spec/provider-components-v1.0.template
  scripts/e2e/bootstrap_job/spec/provider-components.template
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#320 Update to CAPI 0.1.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#327 clusterctl: remove generated machine ssh keys
  config/default/kustomization.yaml
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#323 clusterctl: remove copied kustomization.yaml for Cluster API config
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  config/cluster-api/kustomization.yaml
  config/cluster-api/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#325 clusterctl: remove tabs in machinset yaml template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#316 clusterctl: templatize kubernetes version
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#319 fix CAPV image URLs in build/images/README.md
  build/images/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#326 clusterctl: vsphere provider manager should only run on control plane nodes
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#332 Do not log requeue errors as failures
  pkg/cloud/vsphere/actuators/actuators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#333 Add k/k issue/pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#330 Add clusterctl tools container for generating example yaml
  .gitignore
  Makefile
  cmd/clusterctl/examples/tools/Dockerfile
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  hack/ensure-tools.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#313 Add License Headers To Code And Script Files
  installer/build/bootable/root/etc/profile.d/kubernetes.sh
  installer/build/bootable/root/opt/ova/bin/kubeadm-provisioning.sh
  installer/build/bootable/root/opt/ova/bin/kubernetes-watchdog.sh
  installer/build/scripts/get_logs.sh
  installer/build/scripts/provisioners/provision_kubernetes.sh
  installer/ovatools/ova-ui/templates.go
  pkg/cloud/vsphere/constants/constants.go
  scripts/e2e/bootstrap_job/clusterctl.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#335 Remove building of installer OVA from e2e.sh
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#324 clusterctl: VM folder should be optional
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 clusterctl: generate yaml in docker as current user
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#342 Fixes failed JSON patches
  pkg/cloud/vsphere/context/cluster_context.go
  pkg/cloud/vsphere/context/machine_context.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#340 Correct ssurana github id to sidharthsurana
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 cluster actuator: sync kubeconfig secret
  pkg/cloud/vsphere/actuators/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#345 Update the production image to 0.3.0-alpha.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#308 docs: add getting started guide for bootstrapping a managemenet cluster with clusterctl
  docs/getting_started.md
  docs/machine_images.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#344 clusterctl: disable dhcp6 by default
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  scripts/e2e/bootstrap_job/spec/machines.template
  scripts/e2e/bootstrap_job/spec/machineset.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#349 hack/generate-yaml: templatize sshAuthorizedKeys
  cmd/clusterctl/examples/vsphere/cluster.yaml.template
  docs/getting_started.md
  hack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 Fix the -o OUT_DIR opt for generating yaml
  hack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#351 fix typos in docs/getting_started.md
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#343 re-enable in-tree vsphere cloud provider
  pkg/cloud/vsphere/services/govmomi/create.go
  pkg/cloud/vsphere/services/kubeadm/configs.go
  pkg/cloud/vsphere/services/userdata/controlplane.go
  pkg/cloud/vsphere/services/userdata/controlplane_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#354 add machineset metadata labels
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#357 userdata: use VM Folder in cloud config
  pkg/cloud/vsphere/services/govmomi/create.go
  pkg/cloud/vsphere/services/userdata/controlplane.go
  pkg/cloud/vsphere/services/userdata/controlplane_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#356 Net devices by order, remove invalid IP addrs
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderstatus.yaml
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderstatus_types.go
  pkg/cloud/vsphere/services/govmomi/net/net.go
  pkg/cloud/vsphere/services/govmomi/net/net_test.go
  pkg/cloud/vsphere/services/govmomi/update.go
  pkg/cloud/vsphere/services/govmomi/util.go
  pkg/cloud/vsphere/services/govmomi/vcenter/clone.go
  scripts/e2e/bootstrap_job/spec/provider-components.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#358 Update image to 0.3.0-alpha.1
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#361 Provide Additional Detail For Retrieving Workload Cluster Kubeconfig
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#367 Add new flags to generate-yaml
  hack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#370 Add support for Machine maintenance window
  pkg/cloud/vsphere/actuators/machine/actuator.go
  pkg/cloud/vsphere/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#368 Fix exists logic since Exist doesn't requeue
  pkg/cloud/vsphere/services/govmomi/create.go
  pkg/cloud/vsphere/services/govmomi/delete.go
  pkg/cloud/vsphere/services/govmomi/exists.go
  pkg/cloud/vsphere/services/govmomi/update.go
  pkg/cloud/vsphere/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#362 Change network name for CAPV e2e tests
  scripts/e2e/bootstrap_job/spec/machines.template
  scripts/e2e/bootstrap_job/spec/machineset.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#371 Fix the cloud-init ethernets IDs
  pkg/cloud/vsphere/services/metadata/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#365 add preferred apiserver CIDRs to network devices
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/cloud/vsphere/context/machine_context.go
  scripts/e2e/bootstrap_job/spec/provider-components.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#372 Update to image tag to v0.3.0-beta.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#376 docs/getting_started.md: use new out directory for generate-yaml.sh
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#373 unit test IP addressese from machine context
  pkg/cloud/vsphere/context/machine_context_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#374 docs/getting_started.md: disable dhcp6 in examples
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#375 cluster actuator: don't block delete if kubeconfig secret doesn't exist
  pkg/cloud/vsphere/actuators/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#378 hack/generate-yaml.sh: fix hard-coded cluster name
  hack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#355 Modify -ci image makefile to default to build only
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#381 Updates to build static clusterctl
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#382 fix permissoin issue in make clusterctl-in-docker
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#380 docs: clarify workflow using clusterctl and kubectl
  README.md
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#383 update CAPV image tag to 0.3.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#386 properly log requeue error messages with klogr
  pkg/cloud/vsphere/actuators/actuators.go
  pkg/cloud/vsphere/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#391 Bump etcd start timeout to 30s
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#393 Update object patch logic
  pkg/cloud/vsphere/actuators/actuators.go
  pkg/cloud/vsphere/context/cluster_context.go
  pkg/cloud/vsphere/context/machine_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L
