Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-05, with the labels that each got.

#253 Add support for specifying ntp servers in the MachineSpec
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  cmd/clusterctl/examples/vsphere/machineset.yaml.template
  config/crds/vsphereproviderconfig_v1alpha1_vsphereclusterproviderconfig.yaml
  config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
  docs/design/ntpServers.md
  pkg/apis/vsphereproviderconfig/v1alpha1/vsphereclusterproviderconfig_types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
  pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/vsphere/provisioner/common/templates.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#251 Implements ResourcePool creation and Deploy Direct to Cluster/Host
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#261 populate CloudProviderConfig with credentials from secret
  pkg/cloud/vsphere/provisioner/govmomi/create.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#262 Add namespace flag to limit to a single namespace
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#273 Add ssurana to list of maintainers for CAPV
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#274 Add figo to list of maintainers for CAPV
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS
