Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-02, with the labels that each got.

#187 Fix Syntax Errors in self service quickstart
  docs/self-service/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#193 use MachineList in machine yaml
  cmd/clusterctl/examples/vsphere/machines.yaml.template
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/bootstrap_job/spec/machines.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#190 kubeadm.conf support for multiple k8s versions
  Gopkg.lock
  pkg/cloud/vsphere/provisioner/common/templates.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/create_test.go
  vendor/k8s.io/apimachinery/pkg/util/version/doc.go
  vendor/k8s.io/apimachinery/pkg/util/version/version.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#197 Update the self-service quickstart docs for minikube and kind
  docs/self-service/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#198 Add machineset.yaml to the list of make generated sample yaml
  cmd/clusterctl/examples/vsphere/generate-yaml.sh
  config/default/vsphere_manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Fix recurring VM re-clone issue
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/delete.go
  pkg/cloud/vsphere/provisioner/govmomi/exists.go
  pkg/cloud/vsphere/provisioner/govmomi/update.go
  pkg/cloud/vsphere/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#164 integrate test with OVA build
  installer/build/build-ova.sh
  installer/build/build.sh
  installer/build/container/Dockerfile
  installer/build/container/Makefile
  scripts/e2e/README.md
  scripts/e2e/bootstrap_job.template
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/bootstrap_job/spec/machines.template
  scripts/e2e/bootstrap_secret.template
  scripts/e2e/e2e.sh
  scripts/e2e/hack/bootstrapper.pub
  scripts/e2e/hack/job.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#203 add support for periodic job
  scripts/e2e/e2e.sh
  scripts/e2e/wait_for_job.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#204 handle nil cluster at machine actuator
  .gitignore
  Makefile
  pkg/cloud/vsphere/constants/constants.go
  pkg/cloud/vsphere/provisioner/govmomi/create.go
  pkg/cloud/vsphere/provisioner/govmomi/delete.go
  pkg/cloud/vsphere/provisioner/govmomi/exists.go
  pkg/cloud/vsphere/provisioner/govmomi/update.go
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
