Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-10, with the labels that each got.

#599 CNS docker images were moved from cloudnativestorage/vsphere-block-csi-driver -> vmware/vsphere-block-csi-driver
  examples/default/cluster/cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#598 Fixes to CAPV Docs
  docs/getting_started.md
  examples/default/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#600 default insecure: true in the cloud provider since CAPV doesn't manage vCenter certificates yet
  examples/default/cluster/cluster.yaml
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#601 update vSphere CNS images in getting started guide
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 fix: cleaning up readme.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#604 Updating “Getting Started” and “Troubleshooting” docs with image pull…
  docs/getting_started.md
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#605 add well-known tolerations to released CAPV manager manifest
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#612 🐛 Support running alongside other Cluster API pods in the same namespace with leader election enabled
  main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#613 Updated docs to use K8s v1.15.4 image and added to table
  README.md
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#614 Remove clusterctl build instructions
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#616 add v1.14.7 OVA links to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#618 Parameterized livenessProbe image and registrar image
  api/v1alpha2/cloudprovider/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  examples/default/cluster/cluster.yaml
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#632 drop capv-manager-bootstrap-credentials from infrastructure-components.yaml
  config/default/manager_credentials_patch.yaml
  config/manager/kustomization.yaml
  examples/default/provider-components/capv_manager_bootstrap_credentials.yaml
  examples/default/provider-components/kustomization.yaml
  examples/pre-67u3/provider-components/capv_manager_bootstrap_credentials.yaml
  examples/pre-67u3/provider-components/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#630 use Machine.Name for VM name instead of VSphereMachine.Name
  pkg/cloud/vsphere/services/govmomi/service.go
  pkg/cloud/vsphere/util/machines.go
  pkg/cloud/vsphere/util/machines_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#633 remove StorageClass from addons file
  examples/default/addons.yaml
  examples/pre-67u3/addons.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#634 allow passing a VERSION when generating infrastructure-components.yaml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#637 CAPI 0.2.6
  examples/generate.sh
  go.mod
  go.sum
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#641 Fix idempotency convention link
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#640 Update CSI default images to v1.0.1 on gcr.io
  docs/getting_started.md
  examples/default/cluster/cluster.yaml
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#638 add OVA links for v1.16.1 and v1.16.2
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#642 add liveness probe check to CSI deployments
  pkg/cloud/vsphere/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#643 check vm existence even if machineRef is not set
  pkg/cloud/vsphere/services/govmomi/service.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#646 only document latest Kubernetes patch versions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#648 update default Kubernetes version in docs to v1.16.2
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#649 remove -u from generate manifests usage output
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#651 Add CAPV image disclaimer
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#650 Update CAPBK to v0.1.5
  examples/generate.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S
