Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2019-07, with the labels that each got.

#398 Fix typo in default MB value of VSPHERE_MEM_MIB
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#397 Distroless manager image
  Dockerfile
  config/manager/manager.yaml
  scripts/e2e/bootstrap_job/spec/provider-components.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#394 CAPI 1.4
  go.mod
  go.sum
  scripts/e2e/bootstrap_job/spec/provider-components.template
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/alpha_phase_create_bootstrap_cluster.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/phases/getkubeconfig.go
  vendor/sigs.k8s.io/cluster-api/config/ci/rbac/kustomization.yaml
  vendor/sigs.k8s.io/cluster-api/config/crds/cluster_v1alpha1_machinedeployment.yaml
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/config/rbac/kustomization.yaml
  vendor/sigs.k8s.io/cluster-api/config/rbac/manager_role.yaml
  vendor/sigs.k8s.io/cluster-api/config/rbac/manager_role_binding.yaml
  vendor/sigs.k8s.io/cluster-api/pkg/apis/apis.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/clientset.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/doc.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme/register.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/cluster.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/cluster_client.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/doc.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/generated_expansion.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machine.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machineclass.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machinedeployment.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/machineset.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/error/requeue_error.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/machine_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/providerid.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/remote/cluster.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/remote/util.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#399 docs/getting_started.md: install clusterctl release binary vs building it
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#395 Ready-state logic changes
  cmd/manager/main.go
  pkg/cloud/vsphere/actuators/cluster/actuator.go
  pkg/cloud/vsphere/actuators/machine/actuator.go
  pkg/cloud/vsphere/context/machine_context.go
  pkg/cloud/vsphere/services/govmomi/update.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#389 Fix Kubeadm Init and Join NodeRegistration Options
  pkg/cloud/vsphere/services/govmomi/create.go
  pkg/cloud/vsphere/services/kubeadm/configs_test.go
  pkg/cloud/vsphere/services/kubeadm/noderegistration.go
  pkg/cloud/vsphere/services/kubeadm/noderegistration_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#396 Use pkg/deployer in the Cluster actuator
  cmd/manager/main.go
  pkg/cloud/vsphere/actuators/cluster/actuator.go
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#404 Machine image updates
  build/images/packer/linux/centos/http/7/ks.cfg
  build/images/packer/linux/ubuntu/http/base/preseed.cfg
  hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#411 Recreate VM if it is deleted by infrastructure
  pkg/cloud/vsphere/services/govmomi/update.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#418 Customizable sync period
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#419 Cloud provider credentials as secret
  pkg/cloud/vsphere/actuators/cluster/actuator.go
  pkg/cloud/vsphere/actuators/machine/actuator.go
  pkg/cloud/vsphere/constants/constants.go
  pkg/cloud/vsphere/context/cluster_context.go
  pkg/cloud/vsphere/services/govmomi/create.go
  pkg/cloud/vsphere/services/kubeclient/kubeclient.go
  pkg/cloud/vsphere/services/userdata/controlplane.go
  pkg/cloud/vsphere/services/userdata/controlplane_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#420 Support a custom, default requeue period
  cmd/manager/main.go
  pkg/cloud/vsphere/actuators/cluster/actuator.go
  pkg/cloud/vsphere/actuators/machine/actuator.go
  pkg/cloud/vsphere/config/config.go
  pkg/cloud/vsphere/constants/constants.go
  pkg/cloud/vsphere/services/govmomi/delete.go
  pkg/cloud/vsphere/services/govmomi/update.go
  pkg/cloud/vsphere/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#406 default vmfolder set for cloudconfig
  go.mod
  go.sum
  pkg/cloud/vsphere/services/govmomi/create.go
  vendor/github.com/spf13/afero/.travis.yml
  vendor/github.com/vmware/govmomi/find/finder.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#424 Removes Makefile targets: install, run, deploy
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#422 Format, lint, and check all sources
  Makefile
  go.mod
  go.sum
  hack/check-format.sh
  hack/check-lint.sh
  hack/check-vet.sh
  hack/tools.go
  pkg/cloud/vsphere/services/kubeadm/bootstraptoken.go
  pkg/cloud/vsphere/services/kubeadm/configs.go
  vendor/github.com/mbenkmann/goformat/LICENSE
  vendor/github.com/mbenkmann/goformat/goformat/doc.go
  vendor/github.com/mbenkmann/goformat/goformat/gofmt.go
  vendor/github.com/mbenkmann/goformat/goformat/internal.go
  vendor/github.com/mbenkmann/goformat/goformat/rewrite.go
  vendor/github.com/mbenkmann/goformat/goformat/simplify.go
  vendor/golang.org/x/lint/.travis.yml
  vendor/golang.org/x/lint/CONTRIBUTING.md
  vendor/golang.org/x/lint/LICENSE
  vendor/golang.org/x/lint/README.md
  vendor/golang.org/x/lint/golint/golint.go
  vendor/golang.org/x/lint/golint/import.go
  vendor/golang.org/x/lint/golint/importcomment.go
  vendor/golang.org/x/lint/lint.go
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
  vendor/modules.txt
  vendor/winterdrache.de/goformat/LICENSE
  vendor/winterdrache.de/goformat/printer/nodes.go
  vendor/winterdrache.de/goformat/printer/printer.go
  vendor/winterdrache.de/goformat/tabwriter/tabwriter.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#423 Fix shellcheck issues for scripts/e2e/e2e.sh
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#425 Support markdown linting
  .markdownlintrc
  CONTRIBUTING.md
  README.md
  build/images/README.md
  cmd/clusterctl/examples/vsphere/README.md
  docs/README.md
  docs/design/ntpServers.md
  docs/design/trustedCerts.md
  docs/design/vsphereCredentials.md
  docs/getting_started.md
  docs/machine_images.md
  docs/ova/README.md
  hack/check-mdlint.sh
  hack/tools/mdlint/Dockerfile
  hack/tools/mdlint/Makefile
  scripts/e2e/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#421 Exit early if command fails on bootstrap
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#428 Add a diagram for machine controller reconcile
  docs/design/machine-controller-reconcile.puml
  docs/design/machine-controller-reconcile.svg
Labels: approved, cncf-cla: yes, lgtm, size/L

#430 Update the mdlint tool image
  hack/tools/mdlint/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#388 Update KIND references to v0.4.0
  docs/getting_started.md
  scripts/e2e/create_kind_cluster.sh
  scripts/e2e/kind_config.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#436 Remove sig-vmware from OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#412 Handle YAML generation via image w tools/resources
  docs/getting_started.md
  hack/build-container-images.sh
  hack/generate-yaml.sh
  hack/tools/generate-yaml/Dockerfile
  hack/tools/kustomize/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#434 Fixed export VCENTER_USERNAME in GSG & generate-yaml.sh script
  hack/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#439 Match release tag script
  hack/match-release-tag.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#440 CAPI 0.1.7
  go.mod
  go.sum
  scripts/e2e/bootstrap_job/spec/provider-components.template
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#443 Fix e2e unbound var PULL_PULL_SHA
  scripts/e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#442 Cluster actuator needs delete permission for secret.
  config/rbac/rbac_role.yaml
  pkg/cloud/vsphere/actuators/cluster/actuator.go
  scripts/e2e/bootstrap_job/spec/provider-components.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#446 Relocate scripts for building machine images
  build/images/README.md
  build/images/hack/image-build-ova.py
  build/images/hack/image-govc-cloudinit.sh
  build/images/hack/image-new-kube.py
  build/images/hack/image-post-create-config.sh
  build/images/hack/image-ssh.sh
  build/images/hack/image-tools.sh
  build/images/hack/image-upload.py
  build/images/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#426 Add hack/release.sh script
  hack/build-container-images.sh
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#449 Removed unused Makefile targets
  Makefile
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/e2e.sh
  scripts/e2e/hack/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#452 Update generate-yaml tools for new image location
  hack/generate-yaml.sh
  hack/tools/generate-yaml/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#456 Fix issue generating manifests due to Docker perms
  docs/getting_started.md
  hack/tools/generate-yaml/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#459 docs/getting_started.md: document workaround for linux mount permission issues
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#460 Fix login issues in hack/release.sh
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#462 Create base images for bootstrap and manifests
  hack/tools/bootstrap-base/Dockerfile
  hack/tools/bootstrap-base/Makefile
  hack/tools/manifests-base/Dockerfile
  hack/tools/manifests-base/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#463 Use base images for bootstrap and manifests images
  hack/tools/generate-yaml/Dockerfile
  scripts/e2e/bootstrap_job/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#464 Fixes YAML generation issues with Docker
  docs/getting_started.md
  hack/generate-yaml.sh
  hack/tools/generate-yaml/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#467 docs: don't set CLUSTER_NAME in envvars.txt because it's set with -c
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#466 Troubleshooting guide
  README.md
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#458 CAPI 0.1.8
  go.mod
  go.sum
  scripts/e2e/bootstrap_job/spec/provider-components.template
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M
