Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-01, with the labels that each got.

#706 A Dockerfile with a built-in OpenVPN client for testing
  hack/tools/openvpn/Dockerfile
  hack/tools/openvpn/Makefile
  hack/tools/openvpn/openvpn.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#708 Fix e2e tests by allowing custom CAPI image
  test/e2e/framework/management_cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#709 move e2e tests to use a vpn connection
  hack/e2e.sh
  pkg/util/kubeclient.go
  scripts/ci-test.sh
  scripts/e2e/README.md
  scripts/e2e/bootstrap_job.template
  scripts/e2e/bootstrap_job/Dockerfile
  scripts/e2e/bootstrap_job/Makefile
  scripts/e2e/bootstrap_job/clusterctl.sh
  scripts/e2e/bootstrap_secret.template
  scripts/e2e/create_kind_cluster.sh
  scripts/e2e/e2e.sh
  scripts/e2e/generate-e2e-spec.sh
  scripts/e2e/hack/Dockerfile
  scripts/e2e/hack/Makefile
  scripts/e2e/hack/bootstrapper.pub
  scripts/e2e/hack/job.yml
  scripts/e2e/hack/secret.template
  scripts/e2e/kind_config.template
  scripts/e2e/wait_for_job.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#711 e2e cleanup
  test/e2e/framework/multi_node_control_plane.go
  test/e2e/framework/single_node_control_plane.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#712 Remove vestigial scripts dir
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#716 add clusterctl-settings.json
  .gitignore
  clusterctl-settings.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#715 /etc/hosts update fixes cloudinit vmware reconcile
  docs/getting_started.md
  examples/default/controlplane/controlplane.yaml
  examples/default/machinedeployment/machinedeployment.yaml
  examples/pre-67u3/controlplane/controlplane.yaml
  examples/pre-67u3/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#724 Rename clusterctl-settings file extension
  clusterctl-settings.json
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#721 HAProxy load balancer OVA updates
  hack/tools/haproxy/Makefile
  hack/tools/haproxy/kickstart.json
  hack/tools/haproxy/packer.json
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#727 Update CAPV to use CAPI e2e latest
  Makefile
  go.mod
  go.sum
  hack/e2e.sh
  test/e2e/README.md
  test/e2e/capv_component_generators.go
  test/e2e/capv_resource_generators.go
  test/e2e/capv_test.go
  test/e2e/capv_test_utils.go
  test/e2e/e2e.conf
  test/e2e/framework/clean_up.go
  test/e2e/framework/config.go
  test/e2e/framework/config_test.go
  test/e2e/framework/control_plane.go
  test/e2e/framework/framework_flags.go
  test/e2e/framework/management_cluster.go
  test/e2e/framework/multi_node_control_plane.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#731 Update getting_started.md
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#732 Use upstream's e2e framework config types
  go.mod
  go.sum
  test/e2e/capv_test.go
  test/e2e/e2e.conf
  test/e2e/framework/config.go
  test/e2e/framework/config_test.go
  test/e2e/framework/management_cluster.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#733 Add cluster-api-maintainers to OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#730 Refactor multi-node, control plane e2e test to use KubeadmControlPlane
  pkg/util/machines.go
  test/e2e/capv_resource_generators.go
  test/e2e/capv_test.go
  test/e2e/framework/control_plane.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#725 Add clusterctl labels to CAPV components
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#737 default the kubernetes version to v1.16.2 in the manifest generation
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#736 dump the bootstrap cluster logs into the artifacts directory
  Makefile
  hack/e2e.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#740 wait for KCP nodes to be provisioned
  test/e2e/capv_test.go
  test/e2e/framework/control_plane.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#738 bump csi version to the latest release
  examples/default/cluster/cluster.yaml
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/S
