Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-09, with the labels that each got.

#1022 Adds metadata.yaml for clusterctl contracts
  Makefile
  metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1023 fix typo in getting_started
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1026 Update to CAPI v0.3.9
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1027 Run go mod tidy
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#983 [e2e] Install CNI using ClusterResourceSet and bump up CAPI to v0.3.9
  Makefile
  templates/cluster-template.yaml
  test/e2e/common.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/kustomization.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1021 Fix reconcile of controlplane endpoint in VSphereCluster
  controllers/vspherecluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1025 Use envsubst syntax
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1031 Add check for template disk size
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1029 [e2e] In e2e cluster template, modify cluster CIDR to match with CNI CIDR
  .gitignore
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1032 bump kube-vip to 0.1.8 and adjust leader election params
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1034 move E2Es to kubernetes 1.19.1
  test/e2e/README.md
  test/e2e/config/vsphere-ci.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1019 Add conditions for the reconcile delete workflow
  .gitignore
  controllers/vspherecluster_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  pkg/context/cluster_context.go
Labels: approved, cncf-cla: yes, lgtm, size/M
