Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-05, with the labels that each got.

#909 Remove build tooling for HAProxy OVA
  hack/tools/haproxy/.dockerignore
  hack/tools/haproxy/.gitignore
  hack/tools/haproxy/Dockerfile
  hack/tools/haproxy/Makefile
  hack/tools/haproxy/README.md
  hack/tools/haproxy/ansible/.gitignore
  hack/tools/haproxy/ansible/ansible.cfg
  hack/tools/haproxy/ansible/playbook.retry
  hack/tools/haproxy/ansible/playbook.yml
  hack/tools/haproxy/ansible/roles/cloudinit/tasks/main.yml
  hack/tools/haproxy/ansible/roles/haproxy/files/etc/systemd/system/haproxy.service.d/cloud-init.conf
  hack/tools/haproxy/ansible/roles/haproxy/tasks/main.yml
  hack/tools/haproxy/ansible/roles/pki/files/usr/local/bin/new-ca.sh
  hack/tools/haproxy/ansible/roles/pki/files/usr/local/bin/new-cert.sh
  hack/tools/haproxy/ansible/roles/pki/tasks/main.yml
  hack/tools/haproxy/ansible/roles/sysprep/files/etc/hosts
  hack/tools/haproxy/ansible/roles/sysprep/tasks/main.yml
  hack/tools/haproxy/example/haproxy.cfg
  hack/tools/haproxy/example/id_rsa
  hack/tools/haproxy/example/id_rsa.pub
  hack/tools/haproxy/example/meta-data
  hack/tools/haproxy/example/user-data
  hack/tools/haproxy/hack/image-build-ova.py
  hack/tools/haproxy/hack/image-govc-cloudinit.sh
  hack/tools/haproxy/hack/image-post-create-config.sh
  hack/tools/haproxy/hack/image-ssh.sh
  hack/tools/haproxy/hack/image-tools.sh
  hack/tools/haproxy/hack/image-upload.py
  hack/tools/haproxy/kickstart.json
  hack/tools/haproxy/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#910 generate an empty selector to pass admission
  packaging/flavorgen/flavors/generators.go
  packaging/flavorgen/flavors/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#911 Update README with latest OVAs
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#907 haproxyloadbalancer: Ensure we don't have transactions open
  controllers/haproxyloadbalancer_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#913 Automated cherry pick of #907: haproxyloadbalancer: Ensure we don't have transactions open
  controllers/haproxyloadbalancer_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#915 upgrade csi to v2.0.0 for newly created clusters
  controllers/vspherecluster_controller.go
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#916 Automated cherry pick of #915: upgrade csi to v2.0.0 for newly created clusters
  controllers/vspherecluster_controller.go
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/L
