Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-12, with the labels that each got.

#1058 upgrade CI to CAPI v0.3.11 and fix e2e
  test/e2e/common.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1016 Add support for adding custom vmx keys
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  packaging/flavorgen/flavors/generators.go
  pkg/services/govmomi/extra/config.go
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1053 set the thumbprint to enable secure communications
  api/v1alpha2/vspherecluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/types.go
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/vspherecluster_webhook.go
  api/v1alpha3/vspherecluster_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/webhook/manifests.yaml
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  packaging/flavorgen/flavors/generators.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/vcenter/clone_test.go
  pkg/session/session.go
  test/e2e/config/vsphere-ci.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1062 Move ncdc to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1063 [0.7] Move ncdc to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS
