Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-04, with the labels that each got.

#883 patch early to avoid concurrent clones
  pkg/context/fake/fake_vm_context.go
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#889 remove csi ImagePullPolicy for air-gapped environments
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#899 packaging: Remove machine deployment selector
  go.mod
  go.sum
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#900 Sanitise e2e test script
  Makefile
  hack/e2e.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#898 Add support for passwords with quotation marks, backslashes and tabs when configuring cloud provider and CSI
  api/v1alpha2/cloudprovider_encoding.go
  api/v1alpha2/cloudprovider_encoding_test.go
  api/v1alpha2/cloudprovider_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/cloudprovider_encoding.go
  api/v1alpha3/cloudprovider_encoding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#905 point to the new HAProxy OVA on the getting started docs
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/S
