Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-11, with the labels that each got.

#1045 add the v1alpha4 API changes for CAPV
  docs/roadmap/v1alpha4.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1050 document migration path from haproxy to kube-vip
  docs/migrations.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1049 [CAEP] proposal for failure domain
  docs/proposal/20201103-failure-domain.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1054 Update deps for CAPI and govmomi
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
