Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-08, with the labels that each got.

#963 docs: Add notes on how to do a new release.
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#981 bump kube-vip to 0.1.7
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#982 add quotes around username/password
  config/default/credentials.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#986 Uses CRS to deploy CSI for default flavour
  controllers/vspherecluster_controller.go
  go.sum
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
  packaging/flavorgen/flavors/helpers.go
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#906 External Load Balaner Flavor example
  Makefile
  packaging/flavorgen/cmd/root.go
  packaging/flavorgen/flavors/flavors.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#987 hardcode network interface to eth0 in the cluster-template.yaml
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#988 add docs for v0.7.0
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#989 update mdlint to v0.23.2
  Makefile
  README.md
  hack/tools/mdlint/Dockerfile
  hack/tools/mdlint/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#993 Fix CSI installation for non default templates
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#994 Small fixes to getting started page
  docs/getting_started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1001 check the description before using it in a condition
  pkg/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#997 add dhcp4 and dhcp6 flags in cloud-init metadata only when either of them is set to true
  pkg/util/constants.go
  pkg/util/machines_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1003 let deletion go through when the folder of a VSphereVM doesn't exist
  pkg/services/govmomi/errors.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1005 bump vSphere cloud provider version to 1.2.0
  examples/default/cluster/cluster.yaml
  packaging/flavorgen/flavors/generators.go
  pkg/services/cloudprovider/cloud-controller-manager.go
  test/e2e/data/infrastructure-vsphere/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1013 Fix broken link and table on README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1009 relax the validating webhooks to allow updating the bootstrapRef of VSphereVMs
  api/v1alpha3/vspherevm_webhook.go
  api/v1alpha3/vspherevm_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1017 :seedling: Bump CPI version to v1.2.1
  packaging/flavorgen/flavors/generators.go
  pkg/services/cloudprovider/cloud-controller-manager.go
  test/e2e/data/infrastructure-vsphere/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
