Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-06, with the labels that each got.

#928 README update
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#930 Automated cherry pick of #929: update the latest changes to the csi drivers
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#929 update the latest changes to the csi drivers
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#932 Update go.mod
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#933 cherry pick of #932: update go.mod
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#934 Bump CAPI version to start developing CAPV conditions
  config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#926 Fix race condition that leads to dropping the biosuuid
  controllers/haproxyloadbalancer_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  pkg/services/govmomi/errors.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#936 Automated cherry pick of #926: Fix race condition that leads to dropping the biosuuid
  controllers/haproxyloadbalancer_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  pkg/services/govmomi/errors.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#925 Use DataSecretName to get Bootstrap data
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#937 Automated cherry pick of #925: Use DataSecretName to get Bootstrap data
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
