Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2020-07, with the labels that each got.

#940 Add VSphereCluster conditions
  api/v1alpha2/vspherecluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/condition_consts.go
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  controllers/vspherecluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#946 re-apply the conccurent clones fix
  controllers/vspherevm_controller.go
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#945 bump the kubernetes version we test against
  hack/e2e.sh
  test/e2e/e2e.conf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#935 Add VSphereVM conditions
  api/v1alpha3/condition_consts.go
  api/v1alpha3/vspherevm_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  controllers/vspherevm_controller.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#939 Add VSphereMachine conditions
  api/v1alpha2/vspheremachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/condition_consts.go
  api/v1alpha3/vspheremachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#948 bump govmomi to pickup a config check fix
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#955 haproxyloadbalancer controller: Only reconcile VSphereClusters
  controllers/haproxyloadbalancer_controller.go
  controllers/vspherecluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#962 Automated cherry pick of #946: re-apply the conccurent clones fix
  controllers/vspherevm_controller.go
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#966 :sparkles: Update cluster-api to v0.3.7
  go.mod
  go.sum
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#971 replace featuregate flags to fix the e2e
  hack/e2e.sh
  test/e2e/e2e.conf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#961 Bump gcr.io/cloud-provider-vsphere/cpi/release/manager from v1.0.0 to v1.1.0.
  examples/default/cluster/cluster.yaml
  packaging/flavorgen/flavors/generators.go
  pkg/services/cloudprovider/cloud-controller-manager.go
  test/e2e/capv_resource_generators.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#970 add support for validating webhooks
  api/v1alpha3/types.go
  api/v1alpha3/vspheremachine_webhook.go
  api/v1alpha3/vspheremachine_webhook_test.go
  api/v1alpha3/vspheremachinetemplate_webhook.go
  api/v1alpha3/vspheremachinetemplate_webhooks_test.go
  api/v1alpha3/vspherevm_webhook.go
  api/v1alpha3/vspherevm_webhook_test.go
  api/v1alpha3/webhooks.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/webhookcainjection_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#973 fix validating webhooks to avoid breaking clusterctl move
  .golangci.yml
  api/v1alpha3/vspheremachine_webhook.go
  api/v1alpha3/vspheremachine_webhook_test.go
  api/v1alpha3/vspherevm_webhook.go
  api/v1alpha3/vspherevm_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#957 wait for staticIP to be set in VSphereVM
  controllers/vspherevm_controller.go
  pkg/services/govmomi/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#964 add support for the kube-vip flavor
  Makefile
  packaging/flavorgen/cmd/root.go
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#974 fix boilerplate on webhook tests
  api/v1alpha3/vspheremachine_webhook_test.go
  api/v1alpha3/vspheremachinetemplate_webhooks_test.go
  api/v1alpha3/vspherevm_webhook_test.go
  api/v1alpha3/webhooks.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#976 🐛 relax constraints on the validating webhooks to update ips and enable IPAM use cases
  api/v1alpha3/vspheremachine_webhook.go
  api/v1alpha3/vspheremachine_webhook_test.go
  api/v1alpha3/vspherevm_webhook.go
  api/v1alpha3/vspherevm_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#977 Adds git version to start of controller logs
  Dockerfile
  Makefile
  hack/version.sh
  main.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#978 wait to have IP addresses reported before making a VSphereVM as ready
  controllers/vspherevm_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
