Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2021-05, with the labels that each got.

#1172 fix image links from http to https
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1173 Updates the golang version to 1.16 & k8s version to 1.21
  Dockerfile
  api/v1alpha3/conversion_test.go
  api/v1alpha4/vspherecluster_types.go
  api/v1alpha4/vspherecluster_webhook.go
  api/v1alpha4/vspheremachine_webhook.go
  api/v1alpha4/vspherevm_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  controllers/haproxyloadbalancer_controller.go
  controllers/vspherecluster_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1149 First draft of multi-tenancy proposal
  docs/proposal/20210311-single-controller-multitenancy.md
Labels: approved, cncf-cla: yes, kind/design, lgtm, size/L

#1094 Add the failure domains API
  PROJECT
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/vspheredeploymentzone_types.go
  api/v1alpha3/vspherefailuredomain_types.go
  api/v1alpha3/vspheremachine_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/vspherecluster_types.go
  api/v1alpha4/vspheredeploymentzone_types.go
  api/v1alpha4/vspherefailuredomain_types.go
  api/v1alpha4/vspheremachine_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_vspheredeploymentzones.yaml
  config/crd/patches/cainjection_in_vspherefailuredomains.yaml
  config/crd/patches/webhook_in_vspheredeploymentzones.yaml
  config/crd/patches/webhook_in_vspherefailuredomains.yaml
  config/rbac/vspheredeploymentzone_editor_role.yaml
  config/rbac/vspheredeploymentzone_viewer_role.yaml
  config/rbac/vspherefailuredomain_editor_role.yaml
  config/rbac/vspherefailuredomain_viewer_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1177 add implementation details and API changes
  docs/proposal/20201103-failure-domain.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1185 Copy of PR1059 - move CPI over to CRS and refactor flavorgen
  packaging/flavorgen/cmd/root.go
  packaging/flavorgen/flavors/crs/cpi.go
  packaging/flavorgen/flavors/crs/csi.go
  packaging/flavorgen/flavors/crs/util.go
  packaging/flavorgen/flavors/env/envsubts_consts.go
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
  packaging/flavorgen/flavors/util/helpers.go
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1187 Multi tenancy support for v1alpha3
  api/v1alpha2/vspherecluster_conversion.go
  api/v1alpha3/condition_consts.go
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/vsphereclusteridentity_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/controllers_suite_test.go
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_controller_test.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vsphereclusteridentity_controller_test.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  main.go
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
  pkg/identity/identity.go
  pkg/identity/identity_suite_test.go
  pkg/identity/identity_test.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1188 remove the vspherecluster finalizer when the secret does not exist
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
