Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2021-02, with the labels that each got.

#1102 Modifies vSphereMachine condition status to report for CP to be ready
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1105 Adds new reason to vspheremachine condition
  controllers/vspheremachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1108 Specifies disks in clone spec
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1114 Add missing coordination.k8s.io to ClusterRole for CCM
  pkg/services/cloudprovider/cloud-controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1117 Remove inactive members from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1112 Specifies disks in clone spec
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1111 Utilize datastores found via storage policy
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1118 Utilize datastores found via storage policy
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/M
