Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2021-06, with the labels that each got.

#1190 sets ready condition for VSphereClusterIdentity
  controllers/vsphereclusteridentity_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1192 add checks for network validation on update in vSphereMachine
  api/v1alpha4/vspheremachine_webhook.go
  api/v1alpha4/vspheremachine_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1194 add checks for network validation on update in vSphereMachine #1192 of a3
  api/v1alpha3/vspheremachine_webhook.go
  api/v1alpha3/vspheremachine_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1201 vsphereclusteridentity returns early when secret isn't found
  api/v1alpha3/condition_consts.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vsphereclusteridentity_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1181 Add multi-tenancy support
  api/v1alpha3/condition_consts.go
  api/v1alpha3/vspherecluster_conversion.go
  api/v1alpha3/vspherecluster_types.go
  api/v1alpha3/vsphereclusteridentity_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/condition_consts.go
  api/v1alpha4/vspherecluster_types.go
  api/v1alpha4/vsphereclusteridentity_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/controllers_suite_test.go
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_controller_test.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vsphereclusteridentity_controller_test.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  main.go
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
  pkg/identity/identity.go
  pkg/identity/identity_suite_test.go
  pkg/identity/identity_test.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1161 add keepalive roundtripper to vimClient
  controllers/vspherecluster_controller.go
  controllers/vspherevm_controller.go
  main.go
  pkg/constants/constants.go
  pkg/context/controller_manager_context.go
  pkg/manager/manager.go
  pkg/manager/options.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/vcenter/clone_test.go
  pkg/session/session.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1204 Printcolumn added in VSphereCluster and VSphereMachine
  api/v1alpha4/vspherecluster_types.go
  api/v1alpha4/vspheremachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1193 switches disk move type to the default: moveAllDiskBackingsAndDisallowSharing
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1198 Implement externally managed annotation (also update cluster-api to v0.4.0)
  controllers/vspherecluster_controller.go
  go.mod
  go.sum
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template.yaml
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/log_collector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL
