Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2021-07, with the labels that each got.

#1203 documents identity management
  docs/getting_started.md
  docs/identity_management.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1205 v1a4 changes to document identity management
  docs/getting_started.md
  docs/identity_management.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1143 Refactor manager and options to use controller-runtime structs
  main.go
  pkg/manager/manager.go
  pkg/manager/options.go
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1195 v1a4 switches disk move type to the default: moveAllDiskBackingsAndDisallowSharing…
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1210 Add metadata field to the VSphereMachineTemplate
  api/v1alpha2/vspheremachinetemplate_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1219 Failure Domain: Fixes VM Placement on Hosts
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller_test.go
  pkg/services/govmomi/cluster/cluster_suite_test.go
  pkg/services/govmomi/cluster/rule.go
  pkg/services/govmomi/cluster/service.go
  pkg/services/govmomi/cluster/vmgroup.go
  pkg/services/govmomi/cluster/vmgroup_test.go
  pkg/services/govmomi/metadata/metadata.go
  pkg/services/govmomi/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L
