Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2021-03, with the labels that each got.

#1125 Patches VsphereVM after initiating power on/off tasks
  pkg/services/govmomi/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1126 Automated cherry pick of #1125: Patches VsphereVM after initiating power on/off tasks
  pkg/services/govmomi/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1121 Add missing coordination.k8s.io to ClusterRole for CCM [Cherry-pick into master]
  pkg/services/cloudprovider/cloud-controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1081 Update vsphere-csi-driver release to v2.1.0
  controllers/vspherecluster_controller.go
  packaging/flavorgen/flavors/flavors.go
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1127 Automated cherry pick of #1081: Update vsphere-csi-driver release to v2.1.0
  controllers/vspherecluster_controller.go
  packaging/flavorgen/flavors/flavors.go
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1129 bump capi to v0.3.14
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#1128 bump cloud-provider-vsphere to v1.18.1
  packaging/flavorgen/flavors/generators.go
  pkg/services/cloudprovider/cloud-controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1110 Enable log collection for E2E tests
  .golangci.yml
  go.mod
  hack/e2e.sh
  test/e2e/README.md
  test/e2e/config/vsphere-ci.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/log_collector.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1133 fix panic and randomize chosen datastore when using storage policies
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1135 Add ability to alter vSphereVM thumbprints and tests for it
  api/v1alpha3/vspherevm_webhook.go
  api/v1alpha3/vspherevm_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1136 Updated Zoom link and meeting time.
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1132 Bump cluster-api to v0.3.14
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1131 bump cloud-provider-vsphere to v1.18.1
  packaging/flavorgen/flavors/generators.go
  pkg/services/cloudprovider/cloud-controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1137 [cherry-pick into master] Add ability to alter vSphereVM thumbprints and tests for it
  api/v1alpha3/vspherevm_webhook.go
  api/v1alpha3/vspherevm_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1139 Updates golang version to 1.15.8
  Dockerfile
  go.mod
  hack/tools/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1145 Update klog dependency to v2
  go.mod
  hack/tools/go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1151 fix panic and randomize chosen datastore when using storage policiess
  pkg/services/govmomi/vcenter/clone.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1115 Adds new reason for VMProvisionedCondition
  api/v1alpha3/condition_consts.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  pkg/context/fake/fake_controller_manager_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1154 Adds new reason for VMProvisioning condition
  api/v1alpha3/condition_consts.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  pkg/context/fake/fake_controller_manager_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1153 Make conversion-gen output location explicit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1157 Updates kube-vip version to 0.3.2
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1160 Updates kube-vip version to 0.3.2
  packaging/flavorgen/flavors/generators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1163 Removes topology feature gate
  pkg/services/cloudprovider/csi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
