Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-09, with the labels that each got.

#1607 🌱 Updates kube-vip to 0.5.0
  packaging/flavorgen/flavors/generators.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1602 🌱 Update CAPI to v1.2.1
  .github/workflows/golangci-lint.yaml
  .golangci.yml
  Dockerfile
  apis/v1beta1/vspheredeploymentzone_webhook.go
  apis/v1beta1/vspheremachinetemplate_webhook.go
  apis/v1beta1/vspheremachinetemplate_webhooks_test.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
  config/manager/manager.yaml
  controllers/serviceaccount_controller_suite_test.go
  controllers/svcdiscovery_controller_suite_test.go
  controllers/vmware/test/controllers_suite_test.go
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_reconciler.go
  controllers/vspheremachine_controller.go
  feature/gates.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  packaging/flavorgen/flavors/generators.go
  pkg/identity/identity_test.go
  pkg/record/recorder.go
  pkg/services/govmomi/constants.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  pkg/session/session_test.go
  pkg/util/testutil.go
  test/e2e/capv_clusterclass_quickstart_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/shared/metadata.yaml
  test/helpers/envtest.go
  test/helpers/vcsim/simulator.go
  test/integration/integration_suite_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#1600 🌱 Removes thumbprint value from the CI config
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1606 🌱 Update Calico in e2e tests to v3.24.0
  test/e2e/data/cni/calico/calico.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#1610 ⚠️ Removes test related flags from binary
  controllers/controllers_suite_test.go
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_intg_test.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller.go
  controllers/svcdiscovery_controller_intg_test.go
  controllers/svcdiscovery_controller_suite_test.go
  controllers/svcdiscovery_controller_unit_test.go
  feature/gates.go
  pkg/builder/flags.go
  pkg/builder/test_suite.go
  pkg/builder/testutil.go
  test/helpers/vmware/intg_test_context.go
  test/helpers/vmware/unit_test_context.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1612 ⚠️ Align flag names with upstream Kubernetes & CAPI components
  config/manager/manager.yaml
  main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1617 Automated cherry pick of #1551: Adds API group to e2e script
  hack/e2e.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#1619 Updates CAPI to v1.2.2
  go.mod
  go.sum
  test/e2e/clusterclass_changes_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#1621 Adds RBAC permissions for nodes in core group
  config/rbac/role.yaml
  controllers/vspherevm_controller.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1622 🐛 Fixes panic when reconciling VSphereMachine objects
  controllers/vspheremachine_controller.go
  pkg/services/vimmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#1623 🌱 Exposes a new reason for VMProvisionedCondition
  apis/v1beta1/condition_consts.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  pkg/context/fake/fake_vm_context.go
  pkg/services/fake/vmservice.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1624 spelling
  docs/gpu-pci.md
  docs/roadmap/v1alpha4.md
  docs/troubleshooting.md
Labels: size/XS, lgtm, approved, cncf-cla: yes, needs-ok-to-test

#1634 Adds linting workflow for 1.3 branch
  .github/workflows/golangci-lint.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S
