Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-03, with the labels that each got.

#1463 📖 Change references of branch names to main
  docs/development.md
  hack/release.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes, kind/documentation

#1453 Add USE_EXISTING_CLUSTER variable for e2e tests
  Makefile
  test/e2e/README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1465 🐛 Fixes clusterctl metadata for v1.1.x release
  metadata.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1466 📖 Adds info to update metadata.yaml during release generation
  docs/releasing.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1467 🐛 Automated cherry pick of #1465: Fixes clusterctl metadata for v1.1.x release
  metadata.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1468 E2E test fixes and version bumps for upgrade tests
  go.mod
  go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/govmomi_test.go
  test/integration/data/shared/metadata.yaml
  test/integration/integration-dev.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#1485 Removes usage of deprecated ObjecteMeta field
  pkg/util/machines.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1489 Add legacy `capw` labels to VirtualMachine for backward compatibility
  github.com/lubronzhan/cluster-api-provider-vsphere/apis/v1alpha3/zz_generated.conversion.go
  pkg/services/vmoperator/control_plane_endpoint.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1486 🐛 Delete legacy finalizer, fix setting ownerRef for `VSphereClusterIdentity `
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vsphereclusteridentity_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1497 🐛 Backport secret deletion fix to v1.0.0 from PR #1486
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_controller_test.go
  controllers/vsphereclusteridentity_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1237 Proposal for GPU and PCI passthrough support
  docs/proposal/20210823-gpu-support.md
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1499 Remove the wrongly committed file
  github.com/lubronzhan/cluster-api-provider-vsphere/apis/v1alpha3/zz_generated.conversion.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1451 Refactored GetCredentials Method
  pkg/identity/identity.go
  pkg/identity/identity_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test
