Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-08, with the labels that each got.

#1551 🐛 Delete node explicitly upon deletion of vm
  controllers/vspherevm_controller.go
  hack/e2e.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#1592 📖 Updates current CAPV supported versions
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#1595 Updates CI config for E2E tests
  test/e2e/capi_upgrade_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#1594 🌱 Updates VSphereCluster reconcile request enqueue mechanism
  pkg/util/machines.go
  pkg/util/machines_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1593 Fix markdown tables in test/e2e/README.md
  test/e2e/README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1603 ✨ Adds golang linter GH action
  .github/workflows/golangci-lint.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S
