Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-02, with the labels that each got.

#1389 Align CAPV Makefile targets with CAPI
  Makefile
  apis/v1alpha3/conversion.go
  apis/v1alpha4/conversion.go
  hack/tools/tools.go
  pkg/services/vimmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#1387 🐛 Add missing API type conversions
  Makefile
  apis/v1alpha3/vsphereclusteridentity_conversion.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha3/zz_generated.deepcopy.go
  apis/v1alpha4/vsphereclusteridentity_conversion.go
  apis/v1alpha4/vsphereclustertemplate_conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1alpha4/zz_generated.deepcopy.go
  apis/v1beta1/vsphereclusteridentity_conversion.go
  apis/v1beta1/vsphereclustertemplate_conversion.go
  apis/v1beta1/zz_generated.deepcopy.go
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1399 🐛 upgrade capi to v0.4.7 to fix cert manager issue
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#1401 Upgrade CAPI to v1.0.4 on CAPV release v1.0 to fix cert-manager issue
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#1337 Add serviceAccount, svcDiscovery controller integration tests
  controllers/controllers_suite_test.go
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_intg_test.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller.go
  controllers/svcdiscovery_controller_intg_test.go
  controllers/svcdiscovery_controller_suite_test.go
  controllers/svcdiscovery_controller_unit_test.go
  controllers/vmware/test/controllers_suite_test.go
  controllers/vspherecluster_reconciler_test.go
  go.mod
  go.sum
  pkg/builder/intg_test_context.go
  pkg/builder/test_suite.go
  pkg/builder/testutil.go
  pkg/builder/unit_test_context.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/context/fake/fake_guest_cluster_context.go
  pkg/manager/options.go
  test/e2e/common.go
  test/helpers/envtest.go
  test/integration/integration_suite_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, ok-to-test

#1404 🐛 use correct CAPI version in the require clause in go.mod for release-0.8
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#1405 🐛 use correct CAPI version in the require clause in go.mod in release-1.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#1390 Adds a provision to skip E2E tests
  Makefile
  hack/e2e.sh
  test/e2e/capi_upgrade_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#1409 Fixes CAPI CRD path lookup for envtests
  go.mod
  go.sum
  test/helpers/envtest.go
  test/helpers/mod.go
  test/helpers/mod_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1351 fix virtualnetwork name in configureVirtualMachine
  pkg/services/network/network.go
  pkg/services/network/network_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1412 Bump golangci-lint to v1.44.0 and fix errors
  apis/v1alpha3/cloudprovider_encoding_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/services/network/network.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1416 dynamically create ip-claim name to avoid issues during concurrently running jobs
  hack/e2e.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes, priority/critical-urgent

#1393 ✨ add script to run `verify-conversions` make target
  Makefile
  controllers/serviceaccount_controller_intg_test.go
  hack/boilerplate/boilerplate.py
  hack/verify-api-conversion.sh
Labels: size/L, lgtm, approved, cncf-cla: yes

#1413 Bump kube-vip to v0.4.1
  packaging/flavorgen/flavors/generators.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1371 Re-enable cluster upgrade e2e tests
  test/e2e/capi_upgrade_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1356 Adds provision to check test coverage
  Makefile
  hack/ci-test-coverage.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#1397 Update cluterctl version in e2e to latest patch
  test/e2e/config/vsphere-ci.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes, needs-ok-to-test, priority/critical-urgent

#1433 Fixes CAPI components for upgrade tests
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#1422 🌱 add aggregate cluster-role label to the KCP manager role
  config/rbac/aggregate_kcp_label_to_clusterrole_patch.yaml
  config/rbac/kustomization.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1426 Fixes panic while deployment zone deletion
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#1434 Update k8s version template for CI runs
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/util_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/shared/metadata.yaml
Labels: kind/bug, size/L, priority/important-soon, lgtm, approved, cncf-cla: yes

#1447 Remove extra space in e2e image names
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1411 Adds e2e test for Machine Deployment Rollout test
  test/e2e/capi_machine_deployment_rollout_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test, area/testing

#1459 🌱 make clusterclass test non `PR-Blocking`
  test/e2e/capv_clusterclass_quickstart_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1456 Adds load restrictor flag to template generation
  test/e2e/data/infrastructure-vsphere/kustomization/commons/vcpu.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/mhc-remediation/kcp/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/mhc-remediation/kcp/vcpu.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/node-drain/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, area/testing

#1446 Replace GC_KIND variable with SKIP_RESOURCE_CLEANUP
  Makefile
  test/e2e/README.md
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test
