Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-07, with the labels that each got.

#1555 🌱 Removes failure domain condition from Cluster
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1560 🐛 Fixes role name for worker nodes
  pkg/services/vmoperator/control_plane_endpoint.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1561 🌱 Updates flavorgen to add separate worker template
  packaging/flavorgen/flavors/flavors.go
  test/e2e/data/infrastructure-vsphere/kustomization/conformance/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/conformance/worker-node-md.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/conformance/worker-node-size.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#1264 ✨GPU and PCI passthrough support
  .gitignore
  Makefile
  apis/v1alpha3/conversion_test.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/pci/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/pci/pci-device-template.yaml
  test/e2e/gpu_pci_passthrough_test.go
Labels: lifecycle/active, size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1562 🌱 Adds new version to metadata YAML file
  clusterctl-settings.json
  metadata.yaml
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#1570 OS field and Windows VM name shrink
  apis/v1alpha3/conversion_test.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/types.go
  apis/v1beta1/vspherevm_webhook.go
  apis/v1beta1/vspherevm_webhook_test.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/webhook/manifests.yaml
  packaging/flavorgen/flavors/generators.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1571 Documentation for GPU with PCI
  Makefile
  docs/gpu-pci.md
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1573 Set VSphereMachine.Spec.Volumes zone annotation
  pkg/services/vmoperator/vmopmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#1574 🌱 Adds `go mod download` directive to Dockerfile
  Dockerfile
Labels: lgtm, approved, cncf-cla: yes, size/S

#1576 🌱 Uses cluster name for resource policy creation
  pkg/services/vmoperator/resource_policy.go
  pkg/services/vmoperator/resource_policy_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1581 Use CloudInit bootstrap w VM Operator
  pkg/services/vmoperator/vmopmachine.go
  test/integration/integration_suite_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1583 Switch to CreateOrPatch; ignore manager binary at root of project
  .gitignore
  controllers/serviceaccount_controller.go
  controllers/servicediscovery_controller.go
  pkg/services/network/nsxt_provider.go
  pkg/services/vimmachine.go
  pkg/services/vmoperator/control_plane_endpoint.go
  pkg/services/vmoperator/resource_policy.go
  pkg/services/vmoperator/vmopmachine.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1584 Reuse CAPI bootstrap secret with Supervisor
  pkg/services/vmoperator/constants.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
  pkg/util/testutil.go
  pkg/util/vmware/util.go
  test/integration/cluster_lifecycle_test.go
  test/integration/sanity_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1586 Fix PVC OwnerRef bug for Supervisor
  pkg/services/vmoperator/vmopmachine.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1587 Only set PVC zone annotation when zonal storage classes are required
  pkg/services/vmoperator/vmopmachine.go
Labels: size/XS, lgtm, approved, cncf-cla: yes
