Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-11, with the labels that each got.

#1672 🌱 Automated cherry pick of #1670: Skip creation of cluster modules
  controllers/clustermodule_reconciler.go
  controllers/clustermodule_reconciler_test.go
  pkg/clustermodule/service.go
  pkg/clustermodule/service_test.go
  pkg/clustermodule/session.go
  pkg/context/fake/constants.go
  pkg/context/fake/fake_cluster_context.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1676 🌱 Increases verbosity level for some logs
  pkg/services/govmomi/service.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1664 🌱 Automated cherry pick of #1653: Creates token secret for service account
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1656 ⚠️ Automated cherry pick of #1648: Introduces new flag for setting min TLS version
  main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1675 🐛 Adds ESXi host info label validation and sanitization logic
  controllers/vspheremachine_controller.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1677 🐛 Automated cherry pick of #1675: Adds label validation & sanitization logic
  controllers/vspheremachine_controller.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1678 🐛 Automated cherry pick of #1675: Adds label validation & sanitization logic
  controllers/vspheremachine_controller.go
  pkg/util/label.go
  pkg/util/label_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1657 ✨ Automated cherry pick of #1655: Updates flags for webhook server TLS config
  main.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1618 Maintain flavors in template directory
  Makefile
  docs/gpu-pci.md
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  templates/clusterclass-template.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#1681 :seedling: Run `make generate`
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1686 🌱 Removes storage policy usage from all e2e tests
  .gitignore
  Makefile
  test/e2e/anti_affinity_test.go
  test/e2e/common.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/base/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/commons/remove-storage-policy.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/storage-policy/kustomization.yaml
  test/e2e/node_labeling_test.go
  test/e2e/storage_policy_test.go
Labels: size/L, kind/cleanup, lgtm, approved, cncf-cla: yes

#1429 :sparkles: Add Ignition support
  Makefile
  docs/ignition.md
  packaging/flavorgen/cmd/root.go
  packaging/flavorgen/flavors/flavors.go
  packaging/flavorgen/flavors/generators.go
  pkg/services/govmomi/create.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/esxi/clone.go
  pkg/services/govmomi/extra/config.go
  pkg/services/govmomi/extra/extra_suite_test.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/vcenter/clone.go
  templates/cluster-template-ignition.yaml
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/ignition/ignition.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/ignition/kustomization.yaml
  test/e2e/ignition_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#1666 ✨ Add implementation of Node IPAM support
  apis/v1alpha3/networkdevicespec_conversion.go
  apis/v1alpha3/vspheremachine_conversion.go
  apis/v1alpha3/vspheremachinetemplate_conversion.go
  apis/v1alpha3/vspherevm_conversion.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/networkdevicespec_conversion.go
  apis/v1alpha4/vspheremachine_conversion.go
  apis/v1alpha4/vspheremachinetemplate_conversion.go
  apis/v1alpha4/vspherevm_conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/condition_consts.go
  apis/v1beta1/types.go
  apis/v1beta1/vspherevm_types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/rbac/role.yaml
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  go.mod
  go.sum
  pkg/context/fake/fake_controller_manager_context.go
  pkg/manager/manager.go
  pkg/services/govmomi/context.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/service_test.go
  pkg/util/machines.go
  pkg/util/machines_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, ok-to-test

#1688 🌱 Adds E2E test for VMX version upgrade feature
  Makefile
  test/e2e/common.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/hw-upgrade/kustomization.yaml
  test/e2e/hardware_upgrade_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1692 🐛 Removes hard dependency on cluster module info for VM deletion
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/services/fake/vmservice.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1691 🐛 Check for nil Cluster InfrastructureRef in ClusterModule reconcile
  controllers/clustermodule_reconciler.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1615 ✨ add ability to configure DHCP overrides
  Makefile
  apis/v1alpha3/vspheremachine_conversion.go
  apis/v1alpha3/vspheremachinetemplate_conversion.go
  apis/v1alpha3/vspherevm_conversion.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/vspheremachine_conversion.go
  apis/v1alpha4/vspheremachinetemplate_conversion.go
  apis/v1alpha4/vspherevm_conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  pkg/util/constants.go
  pkg/util/machines_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/dhcp-overrides/dhcp-overrides.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/dhcp-overrides/kustomization.yaml
  test/e2e/dhcp_overrides_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, ok-to-test

#1577 :seedling: Re-enable LB network provider unit-tests
  controllers/vmware/test/controllers_suite_test.go
  controllers/vmware/test/controllers_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, ok-to-test

#1693 🌱 Changes for new minor release v1.5.0
  clusterctl-settings.json
  metadata.yaml
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#1704 🌱 Bump dependencies to fix CVEs
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S
