Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-01, with the labels that each got.

#1329 Fix clusterctl subcommand typo in getting_started
  docs/getting_started.md
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1348 fix vm operator deps
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#1370 Changes for private vCenter URL in CI
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/base/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/base/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#1375 Update OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1379 Cherry pick #1370 to release 0.8
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#1377 Automated cherry pick of #1370: Changes for private vCenter URL in CI
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/base/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/base/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#1381 add quotes to aggregate label role patch yaml
  config/rbac/aggregate_label_to_cluster_role_patch.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1338 add VSphereClusterTemplate to supervisor api group
  apis/vmware/v1beta1/vsphereclustertemplate_types.go
  apis/vmware/v1beta1/zz_generated.deepcopy.go
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/kustomization.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1380 Cherry pick #1370 to release 0.7
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/cluster-cpi-global-config-insecure.yaml
  test/e2e/data/infrastructure-vsphere/kustomization/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#1339 Fix typo in template not found error
  pkg/services/govmomi/template/template.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1344 Quote PATH variable
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1357 Set default e2e artifact folder
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1365 Backport: move datacenter defaulting to resource defaults
  api/v1alpha3/types.go
  api/v1alpha3/vspherefailuredomain_types.go
  api/v1alpha3/vspherefailuredomain_webhook_test.go
  api/v1alpha3/vspheremachine_webhook.go
  api/v1alpha3/vspheremachine_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/webhook/manifests.yaml
  controllers/vspheredeploymentzone_controller_domain_test.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/vcenter/clone_test.go
  pkg/session/session.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1319 Updates Kube-vip image to v0.4.0
  packaging/flavorgen/flavors/generators.go
  test/e2e/data/infrastructure-vsphere/capi-upgrades/v1alpha3/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere/capi-upgrades/v1alpha4/cluster-template.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1301 Implement deletion logic for VSphereDeploymentZone
  apis/v1alpha3/vspheredeploymentzone_conversion.go
  apis/v1alpha3/vspherefailuredomain_conversion.go
  apis/v1alpha4/vspheredeploymentzone_conversion.go
  apis/v1alpha4/vspherefailuredomain_conversion.go
  apis/v1beta1/vspheredeploymentzone_conversion.go
  apis/v1beta1/vspheredeploymentzone_types.go
  apis/v1beta1/vspherefailuredomain_conversion.go
  controllers/controllers_suite_test.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspherevm_controller.go
  pkg/services/vimmachine.go
  pkg/services/vimmachine_test.go
  pkg/util/machines.go
  pkg/util/machines_test.go
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#1236 Support multiple disks on OVA for full clone mode
  apis/v1alpha3/vspheremachine_conversion.go
  apis/v1alpha3/vspheremachinetemplate_conversion.go
  apis/v1alpha3/vspherevm_conversion.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/vspheremachine_conversion.go
  apis/v1alpha4/vspheremachinetemplate_conversion.go
  apis/v1alpha4/vspherevm_conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1382 Adds conditional ginkgo foucs to e2e job
  Makefile
  test/e2e/capv_quick_start_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/storage_policy_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1360 Backport deletion logic for VSphereDeploymentZone
  api/v1alpha3/vspheredeploymentzone_conversion.go
  api/v1alpha3/vspherefailuredomain_conversion.go
  api/v1alpha4/vspheredeploymentzone_conversion.go
  api/v1alpha4/vspheredeploymentzone_types.go
  api/v1alpha4/vspherefailuredomain_conversion.go
  controllers/controllers_suite_test.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspheremachine_controller.go
  controllers/vspheremachine_controller_unit_test.go
  controllers/vspherevm_controller.go
  pkg/util/machines.go
  pkg/util/machines_test.go
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#1386 Introduce override for kube-vip interface
  docs/getting_started.md
  packaging/flavorgen/flavors/env/envsubts_consts.go
  packaging/flavorgen/flavors/generators.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1361 Backport deletion logic for VSphereDeploymentZone
  api/v1alpha3/vspheredeploymentzone_types.go
  controllers/controllers_suite_test.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspheremachine_controller.go
  controllers/vspheremachine_controller_unit_test.go
  controllers/vspherevm_controller.go
  pkg/util/machines.go
  pkg/util/machines_test.go
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/XL
