Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2022-05, with the labels that each got.

#1524 chore: Fix reference link in Makefile
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1522 Move the `keep-alive` functionality out of the feature flag (+ deprecate the flag)
  config/manager/manager.yaml
  controllers/vspherecluster_reconciler.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspherevm_controller.go
  main.go
  pkg/session/session.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#1525 chore: Add apidiff target to Makefile
  Makefile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/tools.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#1527 🌱 Add script to run go-apidiff in a CI context
  hack/ci-apidiff.sh
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#1515 🐛 Fixes logic to fetch credentials of remote cluster
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_intg_test.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller.go
  controllers/svcdiscovery_controller_intg_test.go
  controllers/svcdiscovery_controller_unit_test.go
  pkg/builder/flags.go
  pkg/builder/intg_test_context.go
  pkg/builder/test_suite.go
  pkg/builder/unit_test_context.go
  pkg/context/fake/fake_util.go
  pkg/context/fake/fake_vmware_cluster_context.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#1336 🌱 Adds keep alive support for the session tag manager client
  controllers/session_test.go
  pkg/session/session.go
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#1531 🐛 Add permissions to api-diff script
  hack/ci-apidiff.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1530 🌱 Moves vcsim builder code to remove cyclic dependency
  controllers/vspherecluster_reconciler_test.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspherevm_controller_test.go
  pkg/services/govmomi/cluster/rule_test.go
  pkg/services/govmomi/cluster/service_test.go
  pkg/services/govmomi/cluster/vmgroup_test.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/find/object_test.go
  pkg/services/govmomi/metadata/metadata_suite_test.go
  pkg/session/session_test.go
  test/helpers/envtest.go
  test/helpers/vcsim/builder.go
  test/helpers/vcsim/simulator.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1535 🌱 Bump kube-vip to v0.4.2
  packaging/flavorgen/flavors/generators.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1529 🌱 Updates CAPV manager cluster role
  config/base/kustomization.yaml
  config/base/manager_role_aggregation_patch.yaml
  config/rbac/aggregate_kcp_label_to_clusterrole_patch.yaml
  config/rbac/aggregate_labels.yaml
  config/rbac/aggregate_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/vmware/vspherecluster_reconciler.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1534 🌱 Adds CM environment variables to CAPV manifest
  config/supervisor/add-configmap-env-vars.yaml
  config/supervisor/kustomization.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#1536 🌱 Re-introduces legacy default network label selector
  pkg/services/interfaces.go
  pkg/services/network/constants.go
  pkg/services/network/dummy_provider.go
  pkg/services/network/netop_provider.go
  pkg/services/network/network_test.go
  pkg/services/network/nsxt_provider.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#1537 🌱 Adds release 1.2.0 to metadata file
  metadata.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1505 build: Support arm64 images
  Dockerfile
  Makefile
  docs/development.md
  test/e2e/config/vsphere-ci.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M
