Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2023-11, with the labels that each got.

#2364 :seedling: Upgrade CSI driver to v3.1.0
  go.mod
  go.sum
  packaging/flavorgen/cloudprovider/csi.go
  packaging/flavorgen/cloudprovider/csi/kustomization.yaml
  packaging/flavorgen/cloudprovider/csi/namespace.yaml
  packaging/flavorgen/cloudprovider/csi/vsphere-csi-driver.yaml
  packaging/flavorgen/cmd/root.go
  packaging/flavorgen/flavors/crs/csi.go
  packaging/flavorgen/flavors/crs/types/cloudprovider_types.go
  packaging/flavorgen/flavors/crs/util.go
  packaging/flavorgen/flavors/flavors.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere/main/commons/cluster-resource-set-csi-insecure.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2485 🌱 kubetest: add flake attempts configuration to match upstream tests
  test/e2e/data/kubetest/upstream-e2e-alpha-features.yaml
  test/e2e/data/kubetest/upstream-e2e-serial.yaml
  test/e2e/data/kubetest/upstream-e2e-slow.yaml
  test/e2e/data/kubetest/upstream-e2e.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2486 :seedling: Bump Trivy to v0.47.0
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2463 :sparkles: Bump Cluster API to v1.6.0-beta.1
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller.go
  controllers/servicediscovery_controller_unit_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  go.mod
  go.sum
  main.go
  pkg/context/controller_manager_context.go
  pkg/manager/manager.go
  pkg/services/vmoperator/vmopmachine_test.go
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2429 :seedling: Remove handling for orphaned VSphereMachines
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vspheremachine_controller.go
  controllers/vspheremachine_controller_test.go
  test/e2e/ownerreference_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2493 🌱 Bump to Go 1.20.11
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2484 🌱 Improve logging for `vspherevm_controller` & `vspherevm_ipaddress_reconciler`
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  controllers/vspherevm_ipaddress_reconciler.go
  controllers/vspherevm_ipaddress_reconciler_test.go
  pkg/context/fake/fake_vm_context.go
  pkg/context/vm_context.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/ipam/status_test.go
  pkg/services/govmomi/metadata/metadata_suite_test.go
  pkg/services/govmomi/service_test.go
  pkg/services/govmomi/vcenter/clone.go
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#2508 :seedling: Bump kube-vip to 0.6.3 and enable service mode
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2509 ✨ Adds new field to set the minimum hardware version
  Makefile
  apis/vmware/v1beta1/vspheremachine_types.go
  config/deployments/integration-tests/crds/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  go.mod
  go.sum
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
  pkg/util/testutil.go
  pkg/util/vmx.go
  pkg/util/vmx_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2512 🌱 Fix opentelemetry dependencies to fix CVE
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2498 🌱 Finalize CAPI v1.6.0-beta.1 bump & diagnostics implementation
  Makefile
  README.md
  config/manager/manager.yaml
  config/rbac/role.yaml
  main.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/shared/main/v1beta1/metadata.yaml
  test/integration/integration-dev.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2518 🌱 Bump Cluster API to v1.6.0-rc.0
  Makefile
  go.mod
  go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M
