Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2023-07, with the labels that each got.

#1978 :seedling: Add release-1.7 to Trivy scan
  .github/workflows/scan.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1973 🐛 apis: fix missing categories marker for VShpereVM in v1alpha3 and v1alpha4
  apis/v1alpha3/vspherevm_types.go
  apis/v1alpha4/vspherevm_types.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1966 📖 Update CAPV compatibility specification
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#1974 🌱 test/e2e: add check at anti-affinity test to ensure enough hosts exist
  test/e2e/anti_affinity_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1937 🐛 Fix datastore selection based on StoragePolicy
  pkg/services/govmomi/vcenter/clone.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#1976 :seedling: Drop remediation tests
  test/e2e/mhc_remediation_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1983 🐛 [release-1.6] Makefile: refactor how govc is built to workaround dependency issues building govc
  Makefile
  hack/go-install.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#1986 🌱 Makefile: refactor how govc is built to workaround dependency issues building govc
  Makefile
  hack/go-install.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1988 [release-1.6] 🌱 Bump docker/distribution to v2.8.2
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1989 [release-1.5] :seedling: Bump docker/distribution to v2.8.2 and golang.org/x/net to v0.7.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#1993 [release-1.7] 🌱 Makefile: refactor how govc is built to workaround dependency issues building govc
  Makefile
  hack/go-install.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1931 🐛 envtest: Dynamically load CRDs using golang resolvers
  go.mod
  go.sum
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#1996 🌱 bump CAPI version to v1.5.0-rc.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2003 [release-1.5] 🌱 Add categories to vspherevm CRD YAML
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2004 🌱 Bump controller-tools to v0.12.1
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsourcebindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsources.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_webconsolerequests.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2005 🌱 hack/tools: use go-install.sh for installing controller-gen
  Makefile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2006 [release-1.7] 🌱 hack/tools: use go-install.sh for installing controller-gen for 1.7
  Makefile
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsourcebindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsources.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_webconsolerequests.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/tools.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2007 [release-1.6] 🌱 hack/tools: use go-install.sh for installing controller-gen for 1.6
  Makefile
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsourcebindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsources.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_webconsolerequests.yaml
  config/rbac/role.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/webhook/manifests.yaml
  hack/tools/Makefile
  hack/tools/tools.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2008 [release-1.5] 🌱 hack/tools: use go-install.sh for installing controller-gen for 1.5
  Makefile
  apis/v1beta1/vspherevm_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsourcebindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsources.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/deployments/integration-tests/crds/vmoperator.vmware.com_webconsolerequests.yaml
  config/rbac/role.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/webhook/manifests.yaml
  hack/go-install.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/tools.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#1998 ✨ Support bare IPv6 vCenter server addresses
  pkg/session/session.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2015 🌱 Drop redundant list webhook registrations
  apis/v1beta1/vspheredeploymentzonelist_webhook.go
  apis/v1beta1/vspherefailuredomainlist_webhook.go
  apis/v1beta1/vspheremachinelist_webhook.go
  apis/v1beta1/vspheremachinetemplatelist_webhook.go
  apis/v1beta1/vspherevmlist_webhook.go
  main.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2014 ✨ Disable vAppConfig during VM creation
  pkg/services/govmomi/vcenter/clone.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#2020 🌱 bump github.com/vmware/govmomi to v0.30.6
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2016 🌱 [CI]: Updates CI template to k8s 1.27.3
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2022 🌱 Bump Go to 1.20.6
  Dockerfile
  Makefile
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
Labels: lgtm, approved, cncf-cla: yes, size/S

#2029 🌱 Bump CAPI to v1.5.0-rc.1
  go.mod
  go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2028 🌱 Bump golangci-lint to v1.53.3 and adapt installation from core CAPI
  .github/workflows/golangci-lint.yaml
  .golangci.yml
  Makefile
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
  hack/ensure-golangci-lint.sh
  hack/tools/Makefile
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2035 [release-1.5] 🐛 Don't call session logout for keepAliveHandler
  pkg/session/session.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2034 [release-1.6] 🐛 Don't call session logout for keepAliveHandler
  pkg/session/session.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2033 🐛 pkg/session fix used RoundTripper inside anonymous func for KeepAliveHandler
  pkg/session/session.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2036 🌱 Rename findVMPre7 to findVSphereVM
  pkg/services/vimmachine.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2023 :bug: Return error on session creation if VCentre client not used
  pkg/services/govmomi/create.go
  pkg/services/govmomi/esxi/clone.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2041 🐛 hack/e2e.sh: retry getting ipaddress object name
  hack/e2e.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#2032 🌱 Remove NodeLabeling feature gate
  docs/proposal/node-affinity-and-anti-affinity.md
  feature/feature.go
  main.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2050 ✨ Automate GitHub release creation
  .github/workflows/release.yaml
  .gitignore
  Makefile
  docs/releasing.md
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2067 🌱 [CI]: Updates CI template to k8s 1.27.3
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2057 🌱 Cleanup deleteFunc in VmopMachineService
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2055 🌱 Use pointer receiver consistently in vspheremachine controller
  controllers/vspheremachine_controller.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2068 [release-1.7] ✨ Automate GitHub release creation
  .github/workflows/release.yaml
  .gitignore
  Makefile
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
  docs/releasing.md
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2070 :sparkles: [release-1.5] Automate GitHub release creation
  .github/workflows/release.yaml
  .github/workflows/verify-pr.yml
  .gitignore
  Makefile
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_test.go
  docs/releasing.md
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2081 🌱 Bump docker to v24.0.5
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#1944 :seedling: Improve fd selection logic
  controllers/vspherecluster_reconciler.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2088 [release-1.7] 🌱 Bump golangci-lint to v1.53.3
  .github/workflows/golangci-lint.yaml
  .golangci.yml
  Makefile
  hack/tools/Makefile
Labels: lgtm, approved, cncf-cla: yes, size/M

#2089 [release-1.6] 🌱 Bump golangci-lint to v1.53.3
  .github/workflows/golangci-lint.yaml
  .golangci.yml
  Makefile
  controllers/clustermodule_reconciler.go
  controllers/serviceaccount_controller.go
  controllers/servicediscovery_controller.go
  controllers/vmware/test/controllers_test.go
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  main.go
  pkg/clustermodule/service.go
  pkg/services/govmomi/esxi/clone.go
  pkg/services/network/dummy_provider.go
  pkg/services/network/netop_provider.go
  pkg/services/vmoperator/control_plane_endpoint_test.go
  test/e2e/log_collector.go
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2090 [release-1.5] 🌱 Bump golangci-lint to v1.53.3
  .github/workflows/golangci-lint.yaml
  .golangci.yml
  Makefile
  apis/v1beta1/vspherefailuredomain_webhook_test.go
  apis/v1beta1/vspheremachine_webhook_test.go
  apis/v1beta1/vspherevm_webhook_test.go
  controllers/clustermodule_reconciler.go
  controllers/clustermodule_reconciler_test.go
  controllers/serviceaccount_controller.go
  controllers/servicediscovery_controller.go
  controllers/vmware/test/controllers_test.go
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  main.go
  pkg/clustermodule/service.go
  pkg/services/govmomi/esxi/clone.go
  pkg/services/network/dummy_provider.go
  pkg/services/network/netop_provider.go
  pkg/services/vmoperator/control_plane_endpoint_test.go
  test/e2e/log_collector.go
  test/helpers/envtest.go
  test/integration/integration_suite_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2086 [release-1.5] 🌱 Bump docker to v24.0.5
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2085 [release-1.6] 🌱 Bump docker to v24.0.5
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2080 🌱 Refactor how tools are built to align with CAPI and get rid of tools go.mod
  Makefile
  hack/go-tools-build.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2030 📖 Remove v1alpha4 roadmap
  docs/proposal/20220907-node-affinity-and-anti-affinity.md
  docs/roadmap/v1alpha4.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#2091 🌱 Bump CAPI to v1.5.0
  Makefile
  go.mod
  go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2097 🌱 Prepare metadata.yaml for v1.8 release series
  metadata.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2093 🌱 [CI] Bump setup-envtest
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2100 📖 Update OVAs for K8s 1.27.3
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#2094 [release-1.7] 🌱 Refactor how tools are built to align with CAPI and get rid of tools go.mod
  Makefile
  hack/go-tools-build.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2095 [release-1.6] 🌱 Refactor how tools are built to align with CAPI and get rid of tools go.mod
  Makefile
  hack/go-tools-build.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2096 [release-1.5] 🌱 Refactor how tools are built to align with CAPI and get rid of tools go.mod
  Makefile
  hack/go-tools-build.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2103 🌱 Deprecate AutoConfigure functionality
  .golangci.yml
  apis/v1beta1/vspherefailuredomain_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2108 📖 Remove unused parts from the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#2099 🐛 Refine finalizer handling
  controllers/vmware/test/controllers_test.go
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2104 🌱 align flags with CAPI
  main.go
Labels: size/L, lgtm, approved, cncf-cla: yes
