Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2023-09, with the labels that each got.

#2294 🌱 lint: enable nolintlint and fix findings
  .golangci.yml
  apis/v1alpha3/conversion.go
  apis/v1alpha3/vspherecluster_conversion.go
  apis/v1alpha3/vspheremachine_conversion.go
  apis/v1alpha3/vspheremachinetemplate_conversion.go
  apis/v1alpha3/vspherevm_conversion.go
  apis/v1alpha4/conversion.go
  apis/v1alpha4/vspherecluster_conversion.go
  apis/v1alpha4/vsphereclusteridentity_conversion.go
  apis/v1alpha4/vsphereclusteridentity_types.go
  apis/v1alpha4/vsphereclustertemplate_conversion.go
  apis/v1alpha4/vspheredeploymentzone_conversion.go
  apis/v1alpha4/vspherefailuredomain_conversion.go
  apis/v1alpha4/vspheremachine_conversion.go
  apis/v1alpha4/vspheremachinetemplate_conversion.go
  apis/v1alpha4/vspherevm_conversion.go
  apis/v1beta1/vsphereclustertemplate_webhook.go
  apis/v1beta1/vspheremachine_webhook.go
  apis/v1beta1/vspheremachine_webhook_test.go
  apis/v1beta1/vspherevm_webhook.go
  controllers/vmware/test/controllers_suite_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vspherevm_controller.go
  packaging/flavorgen/flavors/util/helpers.go
  pkg/identity/identity_suite_test.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  test/helpers/envtest.go
  test/helpers/vcsim/simulator.go
  test/helpers/webhook.go
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#2313 :seedling: Bump Trivy to v0.45.0
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2314 📖 docs: fix release-tasks to refer the correct repository
  docs/release/release-tasks.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2309 🌱 Rename controller context and golang context
  controllers/clustermodule_reconciler.go
  controllers/clustermodule_reconciler_test.go
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller.go
  controllers/svcdiscovery_controller_unit_test.go
  controllers/vmware/test/controllers_suite_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vsphereclusteridentity_controller_test.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  controllers/vspherevm_ipaddress_reconciler.go
  controllers/vspherevm_ipaddress_reconciler_test.go
  main.go
  pkg/clustermodule/service.go
  pkg/clustermodule/session.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/identity/identity_suite_test.go
  pkg/manager/manager.go
  pkg/services/fake/vmservice.go
  pkg/services/govmomi/power_test.go
  pkg/services/govmomi/service_test.go
  pkg/services/vimmachine.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/util/testutil.go
  test/helpers/envtest.go
  test/helpers/framework.go
  test/helpers/vmware/intg_test_context.go
  test/integration/integration_suite_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2321 🌱 Improve godoc for VSphereCluster.spec.failureDomainSelector
  apis/v1beta1/vspherecluster_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2327 🌱 fix YML unmarshal error at test code
  controllers/vmware/test/controllers_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2315 🌱 lint: enable `gocritic` configuration and fix findings
  .golangci.yml
  apis/v1alpha3/cloudprovider_encoding_test.go
  apis/v1alpha3/cloudprovider_types.go
  apis/v1alpha3/haproxyloadbalancer_types.go
  apis/v1alpha3/vspherecluster_types.go
  apis/v1alpha4/vspheremachinetemplate_conversion.go
  controllers/controllers_suite_test.go
  controllers/servicediscovery_controller.go
  controllers/vspherecluster_reconciler.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  controllers/vspherevm_controller_test.go
  pkg/manager/manager_test.go
  pkg/manager/options_test.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone_test.go
  pkg/util/label_test.go
  test/e2e/gpu_pci_passthrough_test.go
  test/e2e/log_collector.go
  test/helpers/vmware/intg_test_context.go
  test/helpers/webhook.go
  test/integration/integration_suite_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#2328 🌱 Add codecov
  .github/codecov.yml
  .github/workflows/cover.yaml
  Makefile
  hack/codecov-ignore.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#2316 📖 Document backport policy
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#2330 🌱 Bump to Go 1.20.8
  Dockerfile
  Makefile
  hack/ensure-go.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2322 🌱 Add finalizer for VSphereClusterIdentity
  apis/v1beta1/vsphereclusteridentity_types.go
  controllers/vsphereclusteridentity_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2333 [release-1.6]🌱 Bump to Go 1.19.13
  Dockerfile
  Makefile
  hack/ensure-go.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2332 [release-1.5]🌱 Bump to Go 1.19.13
  Dockerfile
  Makefile
  hack/ensure-go.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2334 [release-1.7] 🌱 Bump to Go 1.19.13
  Dockerfile
  Makefile
  hack/ensure-go.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2341 🌱 Only ensure Go minor version
  hack/ensure-go.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2345 🌱 config: add metrics configuration for kube-state-metrics
  config/metrics/crd-clusterrole.yaml
  config/metrics/crd-metrics-config.yaml
  config/metrics/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2349 🌱 Remove regular quickstart from PR blocking job
  test/e2e/capv_quick_start_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2312 🌱 LDFLAGS defined once for Makefile
  Makefile
  test/e2e/README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#2338 🌱 Add verify-import-restrictions to enforce import restrictions
  Makefile
  apis/.import-restrictions
  apis/v1beta1/.import-restrictions
  apis/vmware/v1beta1/.import-restrictions
  hack/verify-import-restrictions.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#2350 :seedling: Including all packages in coverage
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2339 ✨ Set up golang context when initiating controller manager
  controllers/controllers_suite_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
  main.go
  pkg/manager/manager.go
  pkg/manager/network.go
  pkg/manager/options.go
  test/helpers/envtest.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2209 :seedling: Add ownerReference resilience test
  Makefile
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheremachine_controller.go
  pkg/identity/identity.go
  test/e2e/README.md
  test/e2e/capv_clusterclass_quickstart_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/cluster-identity.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/drop-existing-identity-secret.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/failure-domains.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/vsphereclusteridentity.yaml
  test/e2e/ignition_test.go
  test/e2e/ownerreference_test.go
  test/e2e/quick_start_test.go
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2354 [release-1.8] :seedling: Add ownerReference resilience test
  Makefile
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  pkg/identity/identity.go
  test/e2e/README.md
  test/e2e/capv_clusterclass_quickstart_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/cluster-identity.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/drop-existing-identity-secret.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/failure-domains.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/vsphereclusteridentity.yaml
  test/e2e/ignition_test.go
  test/e2e/ownerreference_test.go
  test/e2e/quick_start_test.go
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2355 [release-1.7] :seedling: Add ownerReference resilience test
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  pkg/identity/identity.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2359 🌱 [release-1.7] Bump to Go 1.20.8
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/ensure-go.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#2361 🌱 [release-1.6] Bump to Go 1.20.8
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/ensure-go.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#2362 🌱 [release-1.5] Bump to Go 1.20.8
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/ensure-go.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#2365 :seedling: Bump Trivy to v0.45.1
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2353 🌱 Get rid of unstructured type in VSphereVM reconciler
  pkg/services/vimmachine.go
  pkg/services/vimmachine_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2352 🌱 Improve logging of VSphereCluster, ProviderServiceAccount and ServiceDiscovery controllers
  .golangci.yml
  controllers/clustermodule_reconciler.go
  controllers/clustermodule_reconciler_test.go
  controllers/controllers_suite_test.go
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller.go
  controllers/servicediscovery_controller_intg_test.go
  controllers/servicediscovery_controller_suite_test.go
  controllers/servicediscovery_controller_unit_test.go
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vmware/vspherecluster_reconciler_test.go
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  main.go
  pkg/clustermodule/fake/service.go
  pkg/clustermodule/interfaces.go
  pkg/clustermodule/service.go
  pkg/clustermodule/service_test.go
  pkg/clustermodule/session.go
  pkg/clustermodule/util_test.go
  pkg/context/cluster_context.go
  pkg/context/fake/fake_cluster_context.go
  pkg/context/fake/fake_guest_cluster_context.go
  pkg/context/fake/fake_machine_context.go
  pkg/context/fake/fake_vmware_cluster_context.go
  pkg/context/vmware/cluster_context.go
  pkg/context/vmware/machine_context.go
  pkg/manager/network.go
  pkg/services/interfaces.go
  pkg/services/network/dummy_provider.go
  pkg/services/network/netop_provider.go
  pkg/services/network/network_test.go
  pkg/services/network/nsxt_provider.go
  pkg/services/vimmachine_test.go
  pkg/services/vmoperator/control_plane_endpoint.go
  pkg/services/vmoperator/control_plane_endpoint_test.go
  pkg/services/vmoperator/resource_policy.go
  pkg/services/vmoperator/resource_policy_test.go
  pkg/services/vmoperator/vmopmachine_test.go
  pkg/session/session.go
  pkg/util/testutil.go
  test/helpers/vmware/unit_test_context.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2369 ✨ refactor context for vspheredeploymentzone controller
  controllers/controllers_suite_test.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  controllers/vspheredeploymentzone_controller_test.go
  main.go
  pkg/services/govmomi/cluster/rule.go
  pkg/services/govmomi/cluster/rule_test.go
  pkg/services/govmomi/cluster/service.go
  pkg/services/govmomi/cluster/vmgroup.go
  pkg/services/govmomi/metadata/metadata.go
  pkg/services/govmomi/metadata/metadata_suite_test.go
  pkg/services/interfaces.go
  pkg/taggable/get.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2375 :seedling: Bump apidiff to v0.7.0
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2374 ✨ refactor context for vsphereclusteridentity controller
  controllers/controllers_suite_test.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vsphereclusteridentity_controller_test.go
  main.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2376 ✨ Refactor context for vspheremachine controller
  controllers/controllers_suite_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vspheremachine_controller.go
  main.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2377 🌱 Use number of esxi hosts as worker node count for anti-affinity e2e test
  test/e2e/anti_affinity_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2379 [release-1.8] 🌱 Use number of esxi hosts as worker node count for anti-affinity e2e test
  test/e2e/anti_affinity_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2378 🌱 lint: remove skip-files for api/v1alpha3
  .golangci.yml
  apis/v1alpha3/cloudprovider_encoding_test.go
  apis/v1alpha3/cloudprovider_types.go
  apis/v1alpha3/conversion.go
  apis/v1alpha3/conversion_test.go
  apis/v1alpha3/networkdevicespec_conversion.go
  apis/v1alpha3/types.go
  apis/v1alpha3/vspherecluster_types.go
  apis/v1alpha3/vsphereclusteridentity_conversion.go
  apis/v1alpha3/vsphereclusteridentity_types.go
  apis/v1alpha3/vspheredeploymentzone_conversion.go
  apis/v1alpha3/vspheredeploymentzone_types.go
  apis/v1alpha3/vspherefailuredomain_conversion.go
  apis/v1alpha3/vspheremachine_types.go
  apis/v1alpha3/vspheremachinetemplate_conversion.go
  apis/v1alpha3/vspherevm_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes, ok-to-test

#2381 🌱 lint: remove linter ignores from .golangci-lint for gosec
  .golangci.yml
  controllers/vspheredeploymentzone_controller_domain.go
  test/e2e/e2e_suite_test.go
  test/e2e/log_collector.go
  test/helpers/mod.go
  test/helpers/vcsim/builder.go
  test/helpers/webhook.go
  test/integration/integration_suite_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2382 🌱 CI: replace metal3 ipam by CAPI in-cluster provider
  hack/e2e.sh
  hack/ipclaim-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2393 :seedling: Fix deprecated markers across codebase
  controllers/vspherecluster_reconciler.go
  pkg/services/network/constants.go
  pkg/services/vmoperator/control_plane_endpoint.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2401 :seedling: Bump Cluster API to v1.5.2
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2402 [release-1.8] :seedling: Bump Cluster API to v1.5.2
  go.mod
  go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2403 :seedling: Bump CAPI test components to v1.5.2
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2404 [release-1.7] :seedling: Bump CAPI test components to v1.4.7
  go.mod
  go.sum
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2351 🐛 Handle missing VSphereFailureDomain on VSphereDeploymentZone deletion
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  controllers/vspheredeploymentzone_controller_test.go
  pkg/context/vspheredeploymentzone_context.go
  pkg/taggable/get.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2405 :bug: flatcar: Run kubeadm after containerd
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template-ignition.yaml
  test/e2e/data/infrastructure-vsphere/main/ignition/ignition.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2407 🌱 Remove nolint usages for gocyclo, paralleltest, wrapcheck and gocognit
  apis/v1alpha3/conversion_test.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
  test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2409 🌱 Remove nolint usages for errcheck, revive, prealloc, goconst, ineffassign
  controllers/vmware/vspherecluster_reconciler.go
  pkg/identity/identity_test.go
  pkg/services/network/dummy_provider.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2410 🌱 remove //nolint:nestif directives
  controllers/vspherecluster_reconciler.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/vimmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test
