Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2023-05, with the labels that each got.

#1901 🌱 add periodic Github job for trivy scanning
  .github/workflows/scan.yaml
  Makefile
  hack/verify-container-images.sh
Labels: size/L, lgtm, approved, cncf-cla: yes

#1907 :bug: Add update to ipaddressclaim rbac
  config/rbac/role.yaml
  controllers/vspherevm_ipaddress_reconciler.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#1910 🌱 Use dl.k8s.io instead of hardcoded GCS URIs
  hack/ensure-kubectl.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1904 🐛 Allow thumbprint update on VSphereVM
  apis/v1beta1/vspherevm_webhook.go
  apis/v1beta1/vspherevm_webhook_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#1902 ✨ Add VMRef moID to Object status
  apis/v1alpha3/conversion_test.go
  apis/v1alpha3/types.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/types.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/types.go
  apis/v1beta1/vspherevm_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  pkg/services/govmomi/service.go
Labels: lgtm, approved, cncf-cla: yes, size/M
