Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2023-03, with the labels that each got.

#1804 :bug: Calculate default primary disk size from base template
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#1809 🌱 Adds junit reporter to the ginkgo command
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1800 ⚠️ Adds missing category field to VSphereVM CRD
  apis/v1beta1/vspherevm_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1721 ✨ ipam display count of address claims bound in condition
  pkg/services/govmomi/service.go
  pkg/services/govmomi/service_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, ok-to-test

#1837 🌱 Removes unnecessary import golang.org/x/net
  go.mod
  pkg/services/govmomi/pci/device.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1835 ✨ Updates kube-vip to v0.5.11
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template-ignition.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#1844 🌱 Updates dependabot config to scan hack/tools directory
  .github/dependabot.yml
Labels: lgtm, approved, cncf-cla: yes, size/S

#1827 📖 Updates template links with latest k8s version
  README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes
