Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2023-10, with the labels that each got.

#2395 🌱 Improve logging for VSphereMachine
  controllers/vspheremachine_controller.go
  pkg/context/fake/fake_machine_context.go
  pkg/context/interfaces.go
  pkg/context/machine_context.go
  pkg/context/vmware/machine_context.go
  pkg/services/interfaces.go
  pkg/services/services_suite_test.go
  pkg/services/vimmachine.go
  pkg/services/vimmachine_test.go
  pkg/services/vmoperator/vmoperator_suite_test.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
  pkg/util/testutil.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2385 :seedling: Move GetMachineDeploymentNameForCluster to usage site
  pkg/services/vmoperator/resource_policy.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/util/vmware/util.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2397 :bug: Remove the conditional on ipv6
  pkg/services/govmomi/ipam/parse.go
  pkg/services/govmomi/ipam/status_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#2416 :seedling: Remove build-dev.sh
  hack/build-dev.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#2415 :seedling: Clarify OWNER_ALIASES file
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2399 🌱 Remove lint ignore for `gocritic`
  controllers/controllers_suite_test.go
  controllers/vspheremachine_controller.go
  pkg/services/govmomi/service.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#2427 🌱 Remove lint ignore for staticcheck
  .golangci.yml
  controllers/vspheredeploymentzone_controller_domain.go
  internal/webhooks/vspherefailuredomain.go
  internal/webhooks/vspherefailuredomain_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2398 ✨ Refactor context for vspherevm controller
  controllers/controllers_suite_test.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  controllers/vspherevm_ipaddress_reconciler.go
  controllers/vspherevm_ipaddress_reconciler_test.go
  main.go
  pkg/services/fake/vmservice.go
  pkg/services/govmomi/cluster/vmgroup.go
  pkg/services/govmomi/cluster/vmgroup_test.go
  pkg/services/govmomi/create.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/ipam/status.go
  pkg/services/govmomi/ipam/status_test.go
  pkg/services/govmomi/power.go
  pkg/services/govmomi/power_test.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/service_test.go
  pkg/services/govmomi/template/template.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/util_test.go
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/interfaces.go
  pkg/util/fetch_object.go
  pkg/util/fetch_object_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, ok-to-test

#2426 🌱 Improve logging for cluster identity controller
  controllers/vsphereclusteridentity_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2413 🌱 Removal of if block usage wrt logging in vsphere machine controller
  pkg/services/vmoperator/vmopmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2432 :seedling: Bump Go to v1.20.10
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2437 :seedling: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2440 [release-1.8] :seedling: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2441 [release-1.6] :seedling: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2442 [release-1.5] :seedling: Bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2438 :seedling: Bump trivy to v0.46.0
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2445 :seedling: Bump Makefile dependency versions
  Makefile
Labels: lgtm, approved, cncf-cla: yes, size/S

#2431 🌱 Remove context from capv customized controller context
  controllers/clustermodule_reconciler_test.go
  controllers/controllers_suite_test.go
  controllers/serviceaccount_controller_intg_test.go
  controllers/serviceaccount_controller_suite_test.go
  controllers/serviceaccount_controller_unit_test.go
  controllers/servicediscovery_controller_intg_test.go
  controllers/servicediscovery_controller_unit_test.go
  controllers/vmware/vspherecluster_reconciler_test.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vsphereclusteridentity_controller_test.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain_test.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  controllers/vspherevm_ipaddress_reconciler_test.go
  main.go
  pkg/clustermodule/service_test.go
  pkg/clustermodule/util.go
  pkg/clustermodule/util_test.go
  pkg/context/controller_manager_context.go
  pkg/context/fake/fake_cluster_context.go
  pkg/context/fake/fake_controller_context.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/context/fake/fake_machine_context.go
  pkg/context/fake/fake_vm_context.go
  pkg/context/fake/fake_vmware_cluster_context.go
  pkg/context/vm_context.go
  pkg/context/vspheredeploymentzone_context.go
  pkg/manager/manager.go
  pkg/services/govmomi/cluster/cluster_suite_test.go
  pkg/services/govmomi/cluster/rule_test.go
  pkg/services/govmomi/cluster/service.go
  pkg/services/govmomi/cluster/service_test.go
  pkg/services/govmomi/cluster/vmgroup_test.go
  pkg/services/govmomi/context.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/ipam/status_test.go
  pkg/services/govmomi/metadata/metadata_suite_test.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/service_test.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  pkg/services/vimmachine_test.go
  pkg/session/session_test.go
  pkg/util/testutil.go
  test/helpers/vmware/intg_test_context.go
  test/helpers/vmware/unit_test_context.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2461 ✨ Prepare main branch for release-1.9 development
  clusterctl-settings.json
  metadata.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2451 ✨ Remove previously deprecated code
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vsphereclusteridentity_controller.go
  test/e2e/data/infrastructure-vsphere/main/ownerreferences/failure-domains.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2436 🌱 Add unit test cases for clustermodule
  pkg/clustermodule/service_test.go
  test/helpers/vcsim/builder.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#2473 :bug: Re-add return on vimmachine error
  pkg/services/vimmachine.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2417 🌱 Add kubetest files for upstream e2e tests
  test/e2e/data/kubetest/upstream-conformance.yaml
  test/e2e/data/kubetest/upstream-e2e-alpha-features.yaml
  test/e2e/data/kubetest/upstream-e2e-serial.yaml
  test/e2e/data/kubetest/upstream-e2e-slow.yaml
  test/e2e/data/kubetest/upstream-e2e.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2467 :bug: Use a cheaper method for storage policy
  go.mod
  go.sum
  pkg/services/govmomi/service.go
  pkg/services/govmomi/service_test.go
  pkg/services/govmomi/storageprofile_util.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2481 [release-1.8] :bug: Use a less expensive method for storage policy
  go.mod
  go.sum
  pkg/services/govmomi/service.go
  pkg/services/govmomi/service_test.go
  pkg/services/govmomi/storageprofile_util.go
Labels: size/L, lgtm, approved, cncf-cla: yes
