Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-02, with the labels that each got.

#2673 🌱 Introduce MODE and TARGET for E2E tests
  Makefile
  docs/release/release-tasks.md
  hack/e2e.sh
  test/e2e/config/config-overrides.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_suite_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2683 🌱 test: remove getClusterctlConfigVariable function and use capi framework functions instead
  test/e2e/e2e_suite_test.go
  test/e2e/govmomi_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2685 🌱 Git ignore config-overrides
  test/e2e/config/.gitignore
  test/e2e/config/config-overrides-example.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2686 🌱 e2e: only upload images to gcs if we run tests which need it
  hack/e2e.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#2688 🌱 Fix vcsim API replacing int with int32
  test/infrastructure/vcsim/api/v1alpha1/controlplaneendpoint_types.go
  test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
  test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
  test/infrastructure/vcsim/api/v1alpha1/zz_generated.deepcopy.go
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_controlplaneendpoints.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vcentersimulators.yaml
  test/infrastructure/vcsim/controllers/controlplaneendpoint_controller.go
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2692 🌱 Make PowerOff move configurable when using vcsim
  test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
  test/infrastructure/vcsim/api/v1alpha1/zz_generated.deepcopy.go
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/controllers/envvar_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2689 [release-1.9] 🌱 e2e: only upload images to gcs if we run tests which need it
  hack/e2e.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#2694 🌱 Use pkgs.k8s.io for apt
  test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2699 🌱 test: fix inject install on bootstrap script
  test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2690 🌱 Move vcsim object naming utils to vcsim helpers
  internal/test/helpers/vcsim/model.go
  internal/test/helpers/vcsim/model_test.go
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2703 🌱 test: run the prekubeadmscript first
  test/e2e/data/infrastructure-vsphere/main/clusterclass/patch-prekubeadmscript.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2693 🌱 Make VirtualMachineClass configurable when using vcsim
  test/framework/vmoperator/vmoperator.go
  test/framework/vmoperator/vmoperator_test.go
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2691 🌱 Align docker build to CAPI
  .dockerignore
  Dockerfile
  Makefile
  hack/e2e.sh
  test/e2e/config/vsphere.yaml
  test/framework/vmoperator/vmoperator.go
  test/infrastructure/vcsim/Dockerfile
  test/integration/integration-dev.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2706 🌱 test: use 5 worker nodes for k8s upgrade + conformance test
  test/e2e/cluster_upgrade_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2707 [release-1.9] 🌱 test: use 5 worker nodes for k8s upgrade + conformance test
  test/e2e/cluster_upgrade_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2681 🌱 hack: add capv-janitor for automated ci cleanup
  Makefile
  hack/tools/janitor/README.md
  hack/tools/janitor/janitor.go
  hack/tools/janitor/main.go
  hack/tools/janitor/vsphere.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2709 🌱 hack: add script to run clean-ci using vpn via prow
  hack/clean-ci.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#2710 🌱 hack: fix janitor to properly set kubeconfig and log an error
  hack/clean-ci.sh
  hack/tools/janitor/main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2711 🌱 hack/janitor: fix printing task id
  hack/tools/janitor/janitor.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2720 🌱 hack: follow up fix from aligning image build process
  hack/e2e.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2717 [release-1.9] 🌱 Test against 1.30 ci latest
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2728 🌱 bump golangci-lint to v1.56.1
  .github/workflows/pr-golangci-lint.yaml
  controllers/clustermodule_reconciler.go
  controllers/clustermodule_reconciler_test.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  internal/test/helpers/envtest.go
  internal/webhooks/vspheredeploymentzone_test.go
  internal/webhooks/vspherefailuredomain_test.go
  internal/webhooks/vspheremachine_test.go
  internal/webhooks/vspheremachinetemplate_test.go
  internal/webhooks/vspherevm_test.go
  packaging/flavorgen/cmd/root.go
  packaging/flavorgen/flavors/crs/types/cloudprovider_encoding.go
  packaging/flavorgen/flavors/crs/types/cloudprovider_encoding_test.go
  pkg/identity/identity_suite_test.go
  pkg/manager/options.go
  pkg/manager/options_test.go
  pkg/services/govmomi/util_test.go
  pkg/session/session.go
  pkg/util/machines_test.go
  pkg/util/supervisor_test.go
  test/infrastructure/tmp-to-be-deleted/runtime/cache/client_test.go
  test/infrastructure/tmp-to-be-deleted/runtime/cache/gc.go
  test/infrastructure/tmp-to-be-deleted/runtime/cache/sync.go
  test/infrastructure/tmp-to-be-deleted/server/api/handler.go
  test/infrastructure/tmp-to-be-deleted/server/api/portforward/httpstreams.go
  test/infrastructure/tmp-to-be-deleted/server/etcd/handler_test.go
  test/infrastructure/tmp-to-be-deleted/server/mux.go
Labels: lgtm, approved, cncf-cla: yes, size/M, area/dependency

#2735 🌱 Bump github.com/vmware/govmomi from 0.34.2 to 0.35.0
  go.mod
  go.sum
  hack/tools/janitor/janitor.go
  pkg/services/govmomi/cluster/vmgroup_test.go
  pkg/services/govmomi/create_test.go
  pkg/services/govmomi/util.go
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/controllers/vmip_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#2729 🌱 Bump kpromo to v4.0.5
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2741 🌱 Bump go 1.21
  .github/workflows/cover.yaml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  hack/ensure-go.sh
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2744 [release-1.9] 🌱 Bump to Go 1.21
  .github/workflows/cover.yaml
  .golangci.yml
  Makefile
  hack/ensure-go.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2743 [release-1.8] 🌱 Bump to Go 1.21
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  Makefile
  hack/ensure-go.sh
  pkg/services/govmomi/util_test.go
  pkg/services/network/nsxt_provider.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2745 [release-1.7] 🌱 Bump to Go 1.21
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  Makefile
  hack/ensure-go.sh
  main.go
  pkg/services/govmomi/util_test.go
  pkg/services/network/nsxt_provider.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2746 📖 README.md: fix formatting
  README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2752 🐛 controllers/test: use APIReader to not assert on cached information
  controllers/serviceaccount_controller_suite_test.go
  controllers/servicediscovery_controller_intg_test.go
  controllers/servicediscovery_controller_suite_test.go
  internal/test/helpers/vmware/intg_test_context.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2762 🌱 [release-1.8] controllers/vmware fix test to not contain data race
  controllers/vmware/test/controllers_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2761 📖 docs: document tagging the test go module
  docs/release/release-tasks.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2757 🌱 test/e2e: implement e2e test for IPAM
  Makefile
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere/main/ipam/ipam-patch.yaml
  test/e2e/data/infrastructure-vsphere/main/ipam/ippool.yaml
  test/e2e/data/infrastructure-vsphere/main/ipam/kustomization.yaml
  test/e2e/data/shared/v1.9/v1beta1_ipam/metadata.yaml
  test/e2e/e2e_setup_test.go
  test/e2e/ipam_test.go
  test/framework/framework.go
  test/framework/ip/addressmanager.go
  test/framework/ip/incluster.go
  test/framework/ip/noop.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2751 🌱 Update Cluster API IPAM version from v1alpha1 to v1beta1
  .golangci.yml
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  controllers/vspherevm_ipaddress_reconciler.go
  controllers/vspherevm_ipaddress_reconciler_test.go
  hack/ipclaim-template.yaml
  hack/tools/janitor/janitor.go
  hack/tools/janitor/main.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/manager/manager.go
  pkg/services/govmomi/ipam/parse.go
  pkg/services/govmomi/ipam/status.go
  pkg/services/govmomi/ipam/status_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#2768 🌱 test: Replace deprecated ginkgo flags
  test/e2e/data/kubetest/conformance-fast.yaml
  test/e2e/data/kubetest/conformance.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2771 🌱 Make Flavor gen templates vcsim friendly
  packaging/flavorgen/flavors/clusterclass_generators.go
  packaging/flavorgen/flavors/env/envsubts_consts.go
  packaging/flavorgen/flavors/generators.go
  packaging/flavorgen/flavors/util/helpers.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  templates/clusterclass-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#2769 🐛 controllers: add 3 second timeout to assertion in test to deflake
  controllers/servicediscovery_controller_suite_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2780 [release-1.8] 🐛 controllers: use apireader to not assert on cached information
  controllers/serviceaccount_controller_suite_test.go
  controllers/svcdiscovery_controller_intg_test.go
  controllers/svcdiscovery_controller_suite_test.go
  test/helpers/vmware/intg_test_context.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2770 🌱 Add leader election to vcsim component yaml
  test/infrastructure/vcsim/config/rbac/kustomization.yaml
  test/infrastructure/vcsim/config/rbac/leader_election_role.yaml
  test/infrastructure/vcsim/config/rbac/leader_election_role_binding.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#2766 ✨ go.mod: Bump capi to main commit 4061a478b1610b308207da434e4eb4fc7af55de7n
  Makefile
  go.mod
  go.sum
  main.go
  pkg/services/vmoperator/vmopmachine.go
  test/go.mod
  test/go.sum
  test/infrastructure/tmp-to-be-deleted/server/mux.go
Labels: size/L, lgtm, approved, cncf-cla: yes
