Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-06, with the labels that each got.

#3030 📖 docs: fix broken ova link
  docs/node-ipam-demo.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3035 🌱 Use absolute paths for folder and resourcePool
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3038 [release-1.8] 🌱 Use absolute paths for folder and resourcePool
  test/e2e/config/vsphere-ci.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3039 [release-1.7] 🌱 Use absolute paths for folder and resourcePool
  test/e2e/config/vsphere-ci.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3041 🌱 Bump Go to 1.21.9
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3033 🌱 Bump to CAPI main (v1.8.0 pre alpha)
  .github/workflows/cover.yaml
  .golangci.yml
  Makefile
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  controllers/clustermodule_reconciler.go
  controllers/servicediscovery_controller.go
  controllers/vspherecluster_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  go.mod
  go.sum
  hack/e2e.sh
  hack/ensure-go.sh
  hack/utils.sh
  hack/verify-go-directive.sh
  test/e2e/e2e_setup_test.go
  test/e2e/ownerrefs_finalizers_test.go
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_controlplaneendpoints.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vcentersimulators.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vmoperatordependencies.yaml
  test/infrastructure/vcsim/config/rbac/role.yaml
  test/infrastructure/vcsim/controllers/vcsim_controller.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3028 🌱 flavorgen: enforce VSPHERE_USERNAME and VSPHERE_PASSWORD variables to be set as string in templates
  packaging/flavorgen/flavors/crs/cpi.go
  packaging/flavorgen/flavors/util/helpers.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  templates/clusterclass-template-supervisor.yaml
  templates/clusterclass-template.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#3034 ✨ test/e2e: use vSphere projects from Boskos
  .dockerignore
  Makefile
  go.mod
  go.sum
  hack/e2e.sh
  hack/tools/boskosctl/Dockerfile
  hack/tools/boskosctl/main.go
  hack/tools/janitor/main.go
  hack/tools/openvpn/Dockerfile
  hack/tools/openvpn/Makefile
  hack/tools/pkg/boskos/client.go
  hack/tools/pkg/boskos/common.go
  hack/tools/pkg/boskos/storage.go
  hack/tools/pkg/janitor/janitor.go
  hack/tools/pkg/janitor/janitor_test.go
  hack/tools/pkg/janitor/vsphere.go
  test/e2e/README.md
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/ipam_test.go
  test/framework/ip/addressmanager.go
  test/framework/ip/incluster.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3051 🌱 cloudbuild: bump images to match capi
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3054 [release-1.9] ✨ test/e2e: use vSphere projects from Boskos
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#3053 [release-1.10] ✨ test/e2e: use vSphere projects from Boskos
  Makefile
  hack/e2e.sh
  test/e2e/README.md
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/ipam_test.go
  test/framework/ip/addressmanager.go
  test/framework/ip/incluster.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3055 [release-1.8] ✨ test/e2e: use vSphere projects from Boskos
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#3056 [release-1.7] ✨ test/e2e: use vSphere projects from Boskos
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#3058 🌱 [release-1.10] Bump cluster-api to v1.7.3
  Makefile
  go.mod
  go.sum
  test/e2e/config/vsphere.yaml
  test/e2e/ownerrefs_finalizers_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3060 🌱 Drop pre-load of cert-manager images in E2E tests
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3057 🌱 Cleanup janitor
  Makefile
  go.mod
  go.sum
  hack/clean-ci.sh
  hack/tools/boskosctl/main.go
  hack/tools/janitor/README.md
  hack/tools/janitor/main.go
  hack/tools/pkg/janitor/janitor.go
  hack/tools/pkg/janitor/janitor_test.go
  hack/tools/pkg/janitor/vsphere.go
  test/e2e/e2e_suite_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3063 🌱 Makefile: add hack/tools to go test
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3052 🌱 Makefile: drop OVERRIDES_DIR and dependent make targets
  Makefile
  docs/development.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#3061 🌱 test: use rolloutStrategy to speed up K8s-Upgrade tests to not hit rollout timeout
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/install-on-bootstrap/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/install-on-bootstrap/set-md-rollout-strategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/set-md-rollout-strategy.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3062 🌱 Bump to golangci-lint v1.59.0
  .github/workflows/pr-golangci-lint.yaml
  test/framework/log/collector.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3065 🌱 [release-1.9] test: use rolloutStrategy to speed up K8s-Upgrade tests to not hit rollout timeout
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/set-md-rollout-strategy.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3066 🌱 Sync dependabot config with core CAPI
  .github/dependabot.yml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3076 🌱 use sha256 thumbprint in tests
  docs/getting_started.md
  test/infrastructure/vcsim/controllers/vcsim_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3074 [release-1.10] ✨ Bump to Go 1.22.4
  .golangci.yml
  Makefile
  hack/ensure-go.sh
  hack/utils.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#3073 [release-1.9] ✨ Bump to Go 1.22.4
  .golangci.yml
  Makefile
  hack/ensure-go.sh
  hack/utils.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#3075 [release-1.8] ✨ Bump to Go 1.22.4
  .golangci.yml
  Makefile
  hack/ensure-go.sh
  hack/utils.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#3077 [release-1.10] 🌱 Makefile: pin controller-gen binary to go 1.21
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3080 [release-1.7] 🌱 Bump govmomi to 0.37.0 for sha256 support
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3078 [release-1.9] 🌱 Bump govmomi to 0.37.0 for sha256 support
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3079 [release-1.8] 🌱 Bump govmomi to 0.37.0 for sha256 support
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S
