Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-03, with the labels that each got.

#2786 🌱 drop hack/tools/bootstrap-base
  hack/tools/bootstrap-base/Dockerfile
  hack/tools/bootstrap-base/Makefile
Labels: lgtm, approved, cncf-cla: yes, size/M

#2787 [release-1.7] 🐛 controllers: update the service in tests if it already exists
  controllers/svcdiscovery_controller_intg_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2785 🌱 add make targets to build and push vm operator image for testing purposes
  .gitignore
  Makefile
  test/infrastructure/vm-operator/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#2767 🌱 Implement E2E test for vcsim in govmomi mode
  Makefile
  hack/e2e.sh
  internal/test/helpers/vcsim/model.go
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/quick_start_test.go
  test/framework/framework.go
  test/framework/ip/addressmanager.go
  test/framework/ip/incluster.go
  test/framework/ip/noop.go
  test/framework/ip/vcsim.go
  test/framework/vcsim/server.go
  test/framework/vmoperator/vmoperator.go
  test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
  test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
  test/infrastructure/vcsim/controllers/controlplaneendpoint_controller.go
  test/infrastructure/vcsim/controllers/controlplaneendpoint_controller_test.go
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller_test.go
  test/infrastructure/vcsim/controllers/vmbootstrap_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller_test.go
  test/infrastructure/vcsim/main.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2796 🐛 Fixes issue with NCP versioning while using the semver package
  pkg/util/networkutil.go
  pkg/util/networkutil_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2790 🌱 test: bump ipam to v1beta1
  test/framework/ip/incluster.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2798 🌱 vm-operator: remove web-validator and set replicas to 1
  Makefile
  test/infrastructure/vm-operator/kustomization.yaml
  test/infrastructure/vm-operator/vm-operator-replicas.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2800 🌱 Add e2e test using supervisor mode with vcsim
  Makefile
  apis/vmware/v1beta1/vspherecluster_types.go
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  hack/e2e.sh
  test/e2e/anti_affinity_test.go
  test/e2e/capi_machine_deployment_rollout_test.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/shared/main/v1beta1_operator/metadata.yaml
  test/e2e/dhcp_overrides_test.go
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gpu_pci_passthrough_test.go
  test/e2e/hardware_upgrade_test.go
  test/e2e/ipam_test.go
  test/e2e/k8s_conformance_test.go
  test/e2e/md_scale_test.go
  test/e2e/node_drain_timeout_test.go
  test/e2e/node_labeling_test.go
  test/e2e/ownerrefs_finalizers_test.go
  test/e2e/quick_start_test.go
  test/e2e/storage_policy_test.go
  test/framework/framework.go
  test/framework/ip/vcsim.go
  test/framework/vmoperator/vmoperator.go
  test/framework/vmoperator/vmoperator_test.go
  test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
  test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
  test/infrastructure/vcsim/api/v1alpha1/vmoperatordependencies_types.go
  test/infrastructure/vcsim/api/v1alpha1/zz_generated.deepcopy.go
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vmoperatordependencies.yaml
  test/infrastructure/vcsim/config/crd/kustomization.yaml
  test/infrastructure/vcsim/config/crd/patches/cainjection_in_vmoperatordependencies.yaml
  test/infrastructure/vcsim/config/default/kustomization.yaml
  test/infrastructure/vcsim/config/rbac/role.yaml
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
  test/infrastructure/vcsim/controllers/vmoperatordependencies_controller.go
  test/infrastructure/vcsim/main.go
  test/infrastructure/vcsim/scripts/vcsim.sh
  test/infrastructure/vm-operator/kustomization.yaml
  test/integration/integration_suite_test.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2803 🌱 Add vm-operator tilt settings
  test/infrastructure/vcsim/tilt-provider.json
  test/infrastructure/vcsim/tilt-provider.yaml
  test/infrastructure/vm-operator/kustomization.yaml
  test/infrastructure/vm-operator/vm-operator-pull-policy.yaml
  tilt-provider.json
  tilt-provider.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2812 🌱 Bump github.com/vmware/govmomi from 0.35.0 to 0.36.1
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2813 🌱 Fix vcsim role to include permissions for protected endpoints
  Makefile
  test/infrastructure/vcsim/config/rbac/role.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2817 🌱 bump Go version to 1.21.8
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2821 [release-1.9] 🌱 bump protobuf to v1.33 to fix CVEs
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2822 🌱 Add GitHub token for release notes action
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2823 🌱 Fix release instructions and release note generation
  Makefile
  docs/release/release-tasks.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2824 [release-1.8] 🌱 bump protobuf -> v1.33 to fix CVEs
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2825 [release-1.7] 🌱 bump protobuf -> v1.33 to fix CVEs
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2827 [release-1.6] 🌱 bump protobuf -> v1.33 to fix CVEs
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2828 🌱 Bump govulncheck to v1.0.4
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2826 [release-1.6] 🌱 Disable govulncheck
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2831 🌱 Use ControlPlaneEndpointIPVariable consistently
  test/e2e/e2e_setup_test.go
  test/e2e/multivc_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2839 🌱 Bump github.com/onsi/gomega from 1.31.1 to 1.32.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2841 🌱 Bump the kubernetes group with 6 updates
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#2840 🌱 Bump github.com/onsi/ginkgo/v2 from 2.16.0 to 2.17.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2846 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up
  apis/vmware/v1beta1/vspherecluster_types.go
  controllers/serviceaccount_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2830 📖 Document vcsim and vm-operator
  test/infrastructure/vcsim/README.md
  test/infrastructure/vcsim/architecture-part1.drawio.svg
  test/infrastructure/vcsim/architecture-part2.drawio.svg
  test/infrastructure/vm-operator/README.md
  test/infrastructure/vm-operator/architecture-part1.drawio.svg
  test/infrastructure/vm-operator/architecture-part2.drawio.svg
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#2850 [release-1.8] 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up
  apis/vmware/v1beta1/vspherecluster_types.go
  controllers/serviceaccount_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2858 🌱 Bump CPI to v1.30.0-alpha
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2859 🌱 Fix noisy logs in vcsim
  test/infrastructure/vcsim/controllers/vmbootstrap_controller.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2857 🌱 Bump Cluster API to v1.7.0-beta.1
  Makefile
  go.mod
  go.sum
  templates/clusterclass-template-supervisor.yaml
  templates/clusterclass-template.yaml
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/shared/caipamic/v0.1/metadata.yaml
  test/e2e/data/shared/capi/v1.5/metadata.yaml
  test/e2e/data/shared/capi/v1.6/metadata.yaml
  test/e2e/data/shared/capi/v1.7/metadata.yaml
  test/e2e/data/shared/capv/main/metadata.yaml
  test/e2e/data/shared/capv/v1.8/metadata.yaml
  test/e2e/data/shared/capv/v1.9/metadata.yaml
  test/e2e/data/shared/vmoperator/v1.8/metadata.yaml
  test/go.mod
  test/go.sum
  test/integration/integration-dev.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#2855 [release-1.7] 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up
  apis/vmware/v1beta1/vspherecluster_types.go
  controllers/serviceaccount_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2856 [release-1.6] 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up
  apis/vmware/v1beta1/vspherecluster_types.go
  controllers/serviceaccount_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2863 🌱 Drop duplicate ClusterCacheTracker log name
  main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes
