Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-07, with the labels that each got.

#3032 :seedling: test: migrate to vm-operator v1alpha2
  test/e2e/e2e_suite_test.go
  test/framework/vmoperator/vmoperator.go
  test/go.sum
  test/infrastructure/vcsim/config/rbac/role.yaml
  test/infrastructure/vcsim/controllers/vcsim_controller.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller_test.go
  test/infrastructure/vcsim/controllers/vspherevm_controller_test.go
  test/infrastructure/vcsim/main.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3085 🌱 controllers: add unit test coverage for esxi host label on supervisor
  controllers/vmware/test/controllers_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3059 🌱 Test OwnerReferences and Finalizers for Supervisor
  Makefile
  go.mod
  go.sum
  packaging/flavorgen/cloudprovider/csi.go
  packaging/flavorgen/flavors/crs/cpi.go
  packaging/flavorgen/flavors/crs/util.go
  packaging/flavorgen/flavors/flavors.go
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/ownerrefs-finalizers/kustomization.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/ownerrefs_finalizers_test.go
  test/framework/vmoperator/vmoperator.go
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller.go
  test/infrastructure/vcsim/controllers/virtualmachine_controller_test.go
  test/infrastructure/vcsim/controllers/vmbootstrap_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3090 🌱 Bump to Go 1.22.5
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3091 🌱 Bump to Go 1.21.12
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3095 [release-1.8] 🌱 Bump govulncheck to 1.0.1
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3089 🌱 test: implement check for all pods running
  test/e2e/quick_start_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3072 🌱 vcsim: implement cluster proxy to allow more e2e tests to be compatible to vcsim
  go.mod
  go.sum
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/e2e_suite_test.go
  test/framework/vcsim/cluster_proxy.go
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/controllers/vmbootstrap_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3024 🌱 Fill up supervisor e2e test - clusterctl upgrades using ClusterClass
  Makefile
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/clusterclass/clusterclass-quick-start-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/clusterclass/patch-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/commons/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/commons/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/workload/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/workload/workload-control-plane-endpoint-ip.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/clusterclass-quick-start-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/patch-controlplaneendpoint.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/patch-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/commons/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/commons/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/workload/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/workload/workload-control-plane-endpoint-ip.yaml
  test/e2e/e2e_setup_test.go
  test/framework/framework.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3096 🌱 test: allow retries creating vcsim
  test/e2e/e2e_suite_test.go
  test/framework/vcsim/server.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3088 🌱 flavorgen: Bump CSI to v3.3.0
  packaging/flavorgen/cloudprovider/csi/README.md
  packaging/flavorgen/cloudprovider/csi/kustomization.yaml
  packaging/flavorgen/cloudprovider/csi/vsphere-csi-driver.yaml
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/base/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/ignition/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/ownerrefs-finalizers/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.10/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/base/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/commons/cluster-resource-set-csi-insecure.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash

#3097 🌱 test: fix wording in vsphere.yaml comment, always use bootstrapClusterProxy to get vCenterSimulator
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_setup_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3025 ✨ vGPU implementation
  apis/v1beta1/types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  docs/gpu-vgpu.md
  internal/webhooks/vspheremachine.go
  internal/webhooks/vspheremachine_test.go
  internal/webhooks/vspheremachinetemplate.go
  internal/webhooks/vspheremachinetemplate_test.go
  pkg/services/govmomi/pci/device.go
  pkg/services/govmomi/pci/device_test.go
  pkg/services/govmomi/vcenter/clone.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3023 🌱 Fill up supervisor e2e test - ClusterClass rollouts
  go.mod
  go.sum
  test/e2e/clusterclass_rollout_test.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#3101 ✨ vGPU implementation - follow-ups
  apis/v1beta1/types.go
  docs/gpu-vgpu.md
  internal/webhooks/vspheremachine.go
Labels: lgtm, approved, cncf-cla: yes, size/S, area/govmomi

#3099 ✨ Implement VirtualMachine namingStrategy
  apis/vmware/v1beta1/vspheremachine_types.go
  apis/vmware/v1beta1/zz_generated.deepcopy.go
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/supervisor/webhook/manifests.yaml
  controllers/vmware/test/controllers_test.go
  internal/webhooks/vmware/vspheremachine_test.go
  internal/webhooks/vmware/vspheremachinetemplate.go
  internal/webhooks/vmware/vspheremachinetemplate_test.go
  main.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vm-namingstrategy.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3104 🌱 Surface more conditions about VirtualMachine pre-prequisites
  pkg/services/vmoperator/vmopmachine.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3105 🌱 Test VirtualMachine pre-requisites only before creation
  pkg/services/vmoperator/vmopmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3107 ✨ Bump CAPI to v1.8.0-beta.0
  Makefile
  controllers/vspherevm_controller_test.go
  go.mod
  go.sum
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/shared/capi/v1.8/metadata.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3108 ✨ Bump CPI to v1.31.0-beta.0
  packaging/flavorgen/cloudprovider/cloud-controller-manager.go
  packaging/flavorgen/cloudprovider/cpi/cpi.yaml
  packaging/flavorgen/flavors/env/envsubts_consts.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.10/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/cluster-template-topology-supervisor.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#3110 🌱 Add release-1.11 to GitHub actions
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3112 🐛 vmoperator: fix nil pointer when reconciling VM
  pkg/services/vmoperator/vmopmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3113 🌱 test: bump core-CAPI v1.8.0-beta.0 to nightly image build
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3109 🌱 test: enable vcsim to run clusterctl upgrade e2e tests
  test/e2e/anti_affinity_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/clusterclass/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/kustomization.yaml
  test/e2e/dhcp_overrides_test.go
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gpu_pci_passthrough_test.go
  test/e2e/hardware_upgrade_test.go
  test/e2e/multivc_test.go
  test/e2e/node_labeling_test.go
  test/e2e/ownerrefs_finalizers_test.go
  test/e2e/storage_policy_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3114 🌱 test: wait for nodes being ready before testing resource versions being stable
  test/e2e/ownerrefs_finalizers_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3118 🌱 Drop WCP fault domains feature gate
  config/deployments/integration-tests/README.md
  config/deployments/integration-tests/crds/topology.tanzu.vmware.com_availabilityzones.yaml
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vmware/vspherecluster_reconciler_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3121 🌱 [release-1.8] test: add env var to allow setting CPI to insecure and use it in CI
  packaging/flavorgen/flavors/crs/util.go
  packaging/flavorgen/flavors/env/envsubts_consts.go
  packaging/flavorgen/flavors/util/helpers.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/config/vsphere-ci.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3123 🌱 Fix flake where VSphereFailureDomain still exists from previous test
  controllers/vspherecluster_reconciler_test.go
  internal/test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3124 🌱 [release-1.9] Bump CAPV to from v1.8.10 and v1.7.7 for upgrade tests
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#3120 🌱 test: dump resources before ValidateResourceVersionStable test
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/ownerrefs_finalizers_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3126 🐛 Fix unit tests, improve debuggability
  controllers/controllers_suite_test.go
  controllers/serviceaccount_controller.go
  controllers/serviceaccount_controller_intg_test.go
  controllers/servicediscovery_controller_intg_test.go
  controllers/vspherecluster_reconciler_test.go
  internal/test/helpers/envtest.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3127 🌱 Bump CAPI to v1.8.0-rc.0
  Makefile
  go.mod
  go.sum
  main.go
  test/e2e/config/vsphere.yaml
  test/extension/main.go
  test/go.mod
  test/go.sum
  test/infrastructure/net-operator/main.go
  test/infrastructure/vcsim/main.go
Labels: size/L, lgtm, approved, cncf-cla: yes
