Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-01, with the labels that each got.

#2586 🌱 Bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2589 [release-1.5] 🌱 Bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2588 [release-1.6] 🌱 Bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#2583 🌱 test: remove kube-vip cleanup
  packaging/flavorgen/flavors/kubevip/files.go
  packaging/flavorgen/flavors/kubevip/kube-vip-cleanup.sh
  packaging/flavorgen/flavors/kubevip/kubevip.go
  packaging/flavorgen/flavors/kubevip/topology.go
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template.yaml
  templates/clusterclass-template.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2577 🌱 Refactor: Get VSphereMachine functions
  controllers/vspherecluster_controller.go
  controllers/vspherecluster_reconciler.go
  controllers/vspheremachine_controller.go
  pkg/services/interfaces.go
  pkg/services/vimmachine.go
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
  pkg/util/machines.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2590 🌱 Ensure vm-operator VM has CAPI cluster-name label
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2591 🌱 Stop relying on GVK being set on regular typed objects
  controllers/serviceaccount_controller_intg_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspherevm_controller_test.go
  controllers/vspherevm_ipaddress_reconciler.go
  internal/test/helpers/vmware/intg_test_context.go
  pkg/context/fake/fake_cluster_context.go
  pkg/context/fake/fake_machine_context.go
  pkg/context/fake/fake_util.go
  pkg/services/govmomi/util.go
  pkg/services/vimmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2599 🌱 Use correct image from main per default when running e2e tests locally
  config/base/manager_image_patch.yaml
  config/manager/manager.yaml
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
  tilt-provider.json
Labels: lgtm, approved, cncf-cla: yes, size/S

#2598 🌱 Sync e2e_suite_test.go with core CAPI
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2602 🌱 [release-1.7] Prevent updating supervisors VSphereMachine.Spec.ResourcePolicyName
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2603 🌱 [release-1.8] Prevent updating supervisors VSphereMachine.Spec.ResourcePolicyName
  pkg/services/vmoperator/vmopmachine.go
  pkg/services/vmoperator/vmopmachine_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2605 🌱 Fix error log when default level cannot be set
  main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2604 🌱 e2e: Stop storing the CAPV image in artifacts
  hack/e2e.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2619 🌱 Bump go-apidiff to v0.8.2
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2620 🌱 Clarify our goals for CAPV releases related to CAPI, CPI and Kubernetes releases
  README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2621 🌱 Fix images in troubleshooting doc
  docs/troubleshooting.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2624 🌱 Bump cloud-provider vsphere to v1.29.0
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2627 🌱 github: add release-1.9 to weekly actions and remove release-1.5
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2628 🌱 github: update md-link check action for release-1.9
  .github/workflows/pr-md-link-check.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2629 🌱 Fail startup if no CRDs are detected
  main.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2635 🌱 Fix ensure-kubectl script
  hack/ensure-kubectl.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2633 🌱 Fail startup if no CRDs are detected
  main.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2641 🌱 Update docs to link to the OVAs in the community-owned GCS bucket
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#2642 🌱 Update docs to link to the OVAs in the community-owned GCS bucket (part II)
  README.md
  docs/getting_started.md
  docs/ignition.md
  docs/node-ipam-demo.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#2630 🌱 Add generate-test-infra-prowjobs makefile target and update docs
  Makefile
  docs/release/release-tasks.md
Labels: lgtm, approved, cncf-cla: yes, size/M

#2625 🌱 flavor-gen: bump CPI manifests and use embed instead of hardcoding
  packaging/flavorgen/cloudprovider/cloud-controller-manager.go
  packaging/flavorgen/cloudprovider/cpi/cpi.yaml
  packaging/flavorgen/cloudprovider/embed.go
  packaging/flavorgen/flavors/crs/cpi.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2654 :seedling: Add laozc to CAPV reviewer
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2612 🌱 e2e: Claim ip addresses dynamically so tests can run in parallel
  Makefile
  hack/e2e.sh
  test/e2e/README.md
  test/e2e/anti_affinity_test.go
  test/e2e/capi_machine_deployment_rollout_test.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/common.go
  test/e2e/dhcp_overrides_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/govmomi_test.go
  test/e2e/gpu_pci_passthrough_test.go
  test/e2e/hardware_upgrade_test.go
  test/e2e/helper/helper.go
  test/e2e/ipam/ipamhelper.go
  test/e2e/ipam/noop.go
  test/e2e/k8s_conformance_test.go
  test/e2e/md_scale_test.go
  test/e2e/multivc_test.go
  test/e2e/node_drain_timeout_test.go
  test/e2e/node_labeling_test.go
  test/e2e/ownerreference_test.go
  test/e2e/quick_start_test.go
  test/e2e/storage_policy_test.go
  test/go.mod
Labels: lgtm, approved, cncf-cla: yes, size/XL

#2658 🌱 hack/e2e.sh fix waiting for ipam
  hack/e2e.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2626 :seedling: test: Ensure finalizers are re-reconciled
  Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerrefs-finalizers/cluster-identity.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerrefs-finalizers/drop-existing-identity-secret.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerrefs-finalizers/failure-domains.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerrefs-finalizers/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/main/ownerrefs-finalizers/vsphereclusteridentity.yaml
  test/e2e/ownerrefs_finalizers_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, ok-to-test

#2655 🌱 flavorgen: bump kubevip to v0.6.4 and import from file
  packaging/flavorgen/flavors/kubevip/files.go
  packaging/flavorgen/flavors/kubevip/kube-vip.yaml
  packaging/flavorgen/flavors/kubevip/kubevip.go
  packaging/flavorgen/flavors/kubevip/topology.go
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#2664 🌱 test: change way to get number of hosts to not rely on read hosts permissions
  test/e2e/anti_affinity_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2661 🐛 kube-vip: fix prepare script to work on pre k8s v1.29
  packaging/flavorgen/flavors/kubevip/kube-vip-prepare.sh
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template.yaml
  templates/clusterclass-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2662 🌱 Refactor test setup
  .golangci.yml
  test/e2e/anti_affinity_test.go
  test/e2e/capi_machine_deployment_rollout_test.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/dhcp_overrides_test.go
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gpu_pci_passthrough_test.go
  test/e2e/hardware_upgrade_test.go
  test/e2e/helper/helper.go
  test/e2e/k8s_conformance_test.go
  test/e2e/md_scale_test.go
  test/e2e/multivc_test.go
  test/e2e/node_drain_timeout_test.go
  test/e2e/node_labeling_test.go
  test/e2e/ownerrefs_finalizers_test.go
  test/e2e/quick_start_test.go
  test/e2e/storage_policy_test.go
  test/framework/ip/addressmanager.go
  test/framework/ip/incluster.go
  test/framework/ip/noop.go
  test/framework/log/collector.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#2663 🌱 test: ignore VMs on errors retrieving the properties
  test/framework/ip/incluster.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2652 🌱 Rename e2e-image
  Makefile
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/integration/integration-dev.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#2671 🌱 test: change labels used for creating IPAddressClaims to not hit the 63 characters length limit
  test/framework/ip/incluster.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#2665 🌱 [release-1.6] test: change way to get number of hosts to not rely on read hosts per…
  test/e2e/anti_affinity_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#2674 🌱 test: fix error handling in incluster ip provider
  test/framework/ip/incluster.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2660 🐛 Fixing vmtoolsd path for/on a flatcar image
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template-ignition.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes, ok-to-test

#2672 🐛 controllers/vmware fix test to not contain data race
  controllers/vmware/test/controllers_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2678 🌱 test: fix log collector for cloud-init
  test/framework/log/collector.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#2594 🌱 Add conformance and upgrade e2e tests
  Makefile
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere-ci.yaml
  test/e2e/config/vsphere-dev.yaml
  test/e2e/data/infrastructure-vsphere/main/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere/main/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
  test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/kustomization.yaml
  test/e2e/k8s_conformance_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#2677 🐛 vspherevm: ensure that the cache gets updated when patching .status.taskRef
  controllers/vspherevm_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S
