Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-10, with the labels that each got.

#3206 🌱 Bump sigs.k8s.io/cluster-api to main@v1.8.0-rc.0.0.20240926091600-d495b4efe59f
  .golangci.yml
  Makefile
  apis/v1alpha3/types.go
  apis/v1alpha3/vendored_cluster_api.go
  apis/v1alpha4/types.go
  apis/v1alpha4/vendored_cluster_api.go
  apis/v1beta1/types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/rbac/role.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  controllers/clustermodule_reconciler.go
  controllers/controllers_suite_test.go
  controllers/vmware/controllers_suite_test.go
  controllers/vmware/serviceaccount_controller.go
  controllers/vmware/servicediscovery_controller.go
  controllers/vmware/servicediscovery_controller_suite_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vmware/vspherecluster_reconciler_test.go
  controllers/vmware/vspheremachinetemplate_controller.go
  controllers/vspherecluster_controller.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  go.mod
  go.sum
  main.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/shared/capi/v1.9/metadata.yaml
  test/extension/main.go
  test/go.mod
  test/go.sum
  test/infrastructure/net-operator/config/rbac/role.yaml
  test/infrastructure/net-operator/controllers/networkinterface_controller.go
  test/infrastructure/net-operator/main.go
  test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_controlplaneendpoints.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vcentersimulators.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vmoperatordependencies.yaml
  test/infrastructure/vcsim/config/rbac/role.yaml
  test/infrastructure/vcsim/controllers/controlplaneendpoint_controller.go
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
  test/infrastructure/vcsim/controllers/vmoperatordependencies_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller.go
  test/infrastructure/vcsim/main.go
Labels: size/XXL, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3215 🌱 main.go: add flags for webhook cert-name and -key
  main.go
  pkg/manager/constants.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3220 🌱 [release-1.10] Improve ReconcileDependencies for VM Operator to handle concurrency on availabityZone changes
  test/framework/vmoperator/vmoperator.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3225 ✨ govmomi: support vCenter 9
  pkg/session/session.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3234 🌱 hack: add script for creating mirror repo PRs
  hack/create-mirror-repository-pr.sh
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/S

#3237 🌱 Makefile: set GOTOOLCHAIN=auto for generate-flavors to make it work in cloudbuild
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3235 :seedling: Fix return messages to contain proper VM information
  pkg/services/govmomi/power.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/util.go
  pkg/services/govmomi/vcenter/clone.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3238 🌱 Switch to using ECR mirror for trivy DB repo
  hack/verify-container-images.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3244 🌱 remove killianmuldoon as maintainer
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cncf-cla: yes
