Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-12, with the labels that each got.

#3277 🌱 e2e: add NodeDrain e2e test
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/e2e/node_drain_test.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#3279 🌱 Bump go v1.22.10
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3281 🌱 [release-1.11] Bump go v1.22.10
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3278 🌱 [release-1.12] e2e: add NodeDrain e2e test
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/e2e/node_drain_test.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#3283 🌱 [release-1.12] test: drop PR-Blocking from node drain test
  test/e2e/node_drain_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3284 🌱 Bump kubernetes release to v1.32.0-rc.1
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3285 🌱 [release-1.12] Bump kubernetes release to v1.32.0-rc.1
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3288 🌱 hack: make create-mirror-repository-pr.sh executable and easier to use
  hack/create-mirror-repository-pr.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3294 ✨ Bump Kubernetes to v1.32 and add new OVA's
  internal/test/helpers/vcsim/model.go
  packaging/flavorgen/cloudprovider/cpi/cpi.yaml
  test/e2e/config/config-overrides-example.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3297 ✨ [release-1.12] Bump Kubernetes to v1.32 and add new OVA's
  internal/test/helpers/vcsim/model.go
  packaging/flavorgen/cloudprovider/cpi/cpi.yaml
  test/e2e/config/config-overrides-example.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#3296 🐛 vspherevm: don't requeue on deletenode when there is no ClusterCache connection
  controllers/vspherevm_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3301 📖 README: add links to Kubernetes v1.32 OVA's and document version support for CAPI v1.9
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#3303 🌱 Bump sigs.k8s.io/cluster-api to v1.9.1
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3304 [release-1.12] 🌱 Bump sigs.k8s.io/cluster-api to v1.9.1
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#3305 🌱 Bump kpromo to 5ab0dbc74b0228c22a93d240596dff77464aee8f
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3214 :sparkles: Add ability to add new data disks to VM during clone process
  Makefile
  apis/v1alpha3/vspheremachine_conversion.go
  apis/v1alpha3/vspheremachinetemplate_conversion.go
  apis/v1alpha3/vspherevm_conversion.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/vspheremachine_conversion.go
  apis/v1alpha4/vspheremachinetemplate_conversion.go
  apis/v1alpha4/vspherevm_conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  docs/proposal/20241003-data-disk-support.md
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/multi-disk/data-disks-patch.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/multi-disk/kustomization.yaml
  test/e2e/multi_disk_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, ok-to-test

#3267 🌱 CI: bump IPAM provider for e2e tests to v1.0
  test/e2e/config/vsphere.yaml
  test/e2e/data/shared/caipamic/v1.0/metadata.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3308 🌱 Minor fixups vsphere.yaml's
  .github/ISSUE_TEMPLATE/release_tracking.md
  test/e2e/config/config-overrides-example.yaml
  test/e2e/config/vsphere.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S
