Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-11, with the labels that each got.

#3246 :bug: Proper ignore IPv6 announcements when IPv6 is not requested
  pkg/util/constants.go
  pkg/util/machines_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3224 ✨ enables explicit disabling of cluster module
  apis/v1alpha3/conversion_test.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/conversion_test.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/vspherecluster_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  controllers/vspherecluster_reconciler.go
  controllers/vspherevm_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash, ok-to-test

#3236 🌱 Replace CAPI's clustercache tracker by the new clustercache
  .golangci.yml
  controllers/controllers_suite_test.go
  controllers/vmware/controllers_suite_test.go
  controllers/vmware/serviceaccount_controller.go
  controllers/vmware/serviceaccount_controller_intg_test.go
  controllers/vmware/servicediscovery_controller.go
  controllers/vmware/servicediscovery_controller_intg_test.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_controller_test.go
  internal/test/helpers/vmware/intg_test_context.go
  main.go
  pkg/context/fake/fake_controller_manager_context.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3249 ✨ Bump to CAPI v1.9.0-beta.0
  Makefile
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/controllers/virtualmachine_controller.go
  test/infrastructure/vcsim/controllers/vmbootstrap_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3250 🌱 Bump CPI to v1.32.0-beta.1
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3254 ✨Bump nsx-operator API mod for the SubnetSet change
  go.mod
  go.sum
  packaging/go.sum
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3229 :sparkles: Allow using moid
  apis/v1beta1/types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  pkg/context/fake/fake_vm_context.go
  pkg/services/govmomi/create_test.go
  test/e2e/e2e_setup_test.go
  test/e2e/quick_start_test.go
  test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vspherevm_controller.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3049 ✨ Add NetworkConfigurations, VMTemplate to FailureDomain
  apis/v1alpha3/topology_conversion.go
  apis/v1alpha3/vspherefailuredomain_conversion.go
  apis/v1alpha3/zz_generated.conversion.go
  apis/v1alpha4/topology_conversion.go
  apis/v1alpha4/vspherefailuredomain_conversion.go
  apis/v1alpha4/zz_generated.conversion.go
  apis/v1beta1/vspherefailuredomain_types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  controllers/vspheredeploymentzone_controller_domain.go
  internal/webhooks/vspherefailuredomain.go
  internal/webhooks/vspherefailuredomain_test.go
  pkg/services/vimmachine.go
  pkg/services/vimmachine_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash, ok-to-test

#3259 🌱 Bump sigs.k8s.io/cluster-api to v1.9.0-beta.1
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3263 🌱 Bump sigs.k8s.io/cluster-api to v1.9.0-rc.0
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3266 🌱 Update branch matrix for weekly GitHub actions
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3264 🌱 CI: Bump Kubernetes version to v1.32.0-rc.0
  test/e2e/config/vsphere.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3265 [release-1.12] 🌱 Set base branch correctly for link checker
  .github/workflows/pr-md-link-check.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3269 🌱 Bump CPI to v1.32.0-rc.0
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3272 [release-1.12] 🌱 test: do not test latest-1.33 on 1.12 branch
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes
