Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-08, with the labels that each got.

#3129 🌱 test: Bump CPI to v1.31.0-rc.0
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3131 🐛 Drop caBundle from CRDs to support Kubernetes 1.31
  config/default/crd/patches/webhook_in_vsphereclusters.yaml
  config/default/crd/patches/webhook_in_vsphereclustertemplates.yaml
  config/default/crd/patches/webhook_in_vspheredeploymentzones.yaml
  config/default/crd/patches/webhook_in_vspherefailuredomains.yaml
  config/default/crd/patches/webhook_in_vspheremachines.yaml
  config/default/crd/patches/webhook_in_vspheremachinetemplates.yaml
  config/default/crd/patches/webhook_in_vspherevms.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3136 🌱 Improve checking if guest cluster client works in unit tests
  controllers/serviceaccount_controller_intg_test.go
  controllers/servicediscovery_controller_intg_test.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3137 🌱 e2e: introduce and use KUBERNETES_VERSION_MANAGEMENT variable which builds kindest/node image on demand
  hack/ci-e2e-lib.sh
  hack/e2e.sh
  test/e2e/config/vsphere.yaml
  test/framework/framework.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3142 ✨ Bump Cluster API to v1.8.0-rc.1
  go.mod
  go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3144 🌱 Bump CPI to v1.31.0-rc.1
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3145 🌱 test: ensure we can collect machine logs
  test/framework/log/collector.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3147 🌱 testutil: fix import name for fake client library
  pkg/util/testutil.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3149 🌱 packaging: write kubeadm script log for ignition
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template-ignition.yaml
  test/framework/log/collector.go
Labels: lgtm, approved, cncf-cla: yes, size/S

#3138 🌱 Bump Kubernetes version in tests to 1.31.0-rc.1
  .gitignore
  Makefile
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/base/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/base/patch-k8s-install-script-kcp.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/base/patch-k8s-install-script-kct.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass-runtimesdk/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-k8s-install-script.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/fast-rollout/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/fast-rollout/set-md-rollout-strategy.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/ignition/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/base/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/base/patch-k8s-install-script-kcp.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/base/patch-k8s-install-script-kct.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass-runtimesdk/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-k8s-install-script.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/fast-rollout/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/fast-rollout/set-md-rollout-strategy.yaml
  test/e2e/k8s_conformance_test.go
  test/extension/handlers/topologymutation/handler.go
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3151 ✨ Bump CAPI to v1.8.0
  Makefile
  go.mod
  go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3154 ✨ Bump e2e tests to kubernetes v1.31.0
  internal/test/helpers/vcsim/model.go
  packaging/flavorgen/cloudprovider/cpi/cpi.yaml
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/config/config-overrides-example.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3155 ✨ Bump CAPI to v1.8.1 and CPI to v1.31.0
  Makefile
  go.mod
  go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3157 📖 README.md: add information about v1.31.0 OVA's
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#3158 📖 README.md update supported versions to CAPI v1.8
  README.md
Labels: lgtm, approved, cncf-cla: yes, size/S

#3156 🌱 Bump ubuntu to 24.04 images
  internal/test/helpers/vcsim/model.go
  test/e2e/config/config-overrides-example.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3111 [release-1.11] 🌱 Set base branch correctly for link checker
  .github/workflows/pr-md-link-check.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3159 🌱 Prepare main branch for v1.12 development
  Makefile
  clusterctl-settings.json
  docs/release/release-tasks.md
  metadata.yaml
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/clusterclass/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/clusterclass/patch-k8s-install-script.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/clusterclass/patch-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/commons/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/commons/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/workload/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/workload/workload-control-plane-endpoint-ip.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/clusterclass-quick-start-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/patch-k8s-install-script.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/patch-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/patch-vm-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/commons/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/commons/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/workload/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/workload/workload-control-plane-endpoint-ip.yaml
  test/e2e/data/shared/capv/main/metadata.yaml
  test/e2e/data/shared/capv/v1.11/metadata.yaml
  test/extension/tilt-provider.yaml
  test/infrastructure/net-operator/tilt-provider.yaml
  test/infrastructure/vcsim/tilt-provider.yaml
  tilt-provider.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes

#3160 🌱 golangci-lint: only exclude specific deprecations
  .golangci.yml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3163 🌱 test: use ubuntu 24.04 in Runtime SDK test
  test/extension/handlers/topologymutation/handler.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3128 ✨ Enable NSX LB healthcheck on kube-apiserver
  .golangci.yml
  config/rbac/role.yaml
  controllers/vmware/vspherecluster_reconciler.go
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/services/network/constants.go
  pkg/services/network/network_test.go
  pkg/services/network/nsxt_vpc_provider.go
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3174 🌱 Bump nsx-operator API mod
  go.mod
  go.sum
  pkg/services/network/network_test.go
  pkg/services/network/nsxt_vpc_provider.go
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3176 🌱 test: Bump autoscaler to v1.31.0
  test/e2e/autoscaler_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes
