Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2024-09, with the labels that each got.

#3178 🐛 Small test fix. Remove OwnerReference & Check for Finalizers being empty
  controllers/vspherecluster_reconciler_test.go
Labels: kind/cleanup, lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#3148 🌱 test: check failureDomains on VSphereCluster in e2e test
  test/e2e/data/infrastructure-vsphere-govmomi/main/ownerrefs-finalizers/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/ownerrefs-finalizers/vspherecluster-failuredomainselector.yaml
  test/e2e/ownerrefs_finalizers_test.go
  test/infrastructure/vcsim/controllers/envvar_controller.go
  test/infrastructure/vcsim/controllers/vcsim_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3184 🌱 Bump sigs.k8s.io/cluster-api to v1.8.2
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3188 🌱 Verify PR titles with shell script
  .github/workflows/pr-verify.yaml
  hack/verify-pr-title.sh
Labels: lgtm, approved, cncf-cla: yes, size/M

#3189 📖 Update CAPV meeting time
  README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3200 🌱 csi: use images from new location
  packaging/flavorgen/cloudprovider/csi/vsphere-csi-driver.yaml
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.10/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/cluster-template-topology-supervisor.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#3201 🌱 [release-1.11] csi: use images from new location
  packaging/flavorgen/cloudprovider/csi/vsphere-csi-driver.yaml
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.10/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/cluster-template-topology-supervisor.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#3202 🌱 [release-1.10] csi: use images from new location
  packaging/flavorgen/cloudprovider/cloud-controller-manager.go
  packaging/flavorgen/cloudprovider/cpi/cpi.yaml
  packaging/flavorgen/cloudprovider/csi/kustomization.yaml
  packaging/flavorgen/flavors/env/envsubts_consts.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template-topology-supervisor.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.8/base/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.8/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.8/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/base/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3203 🌱 [release-1.9] csi: use images from new location
  packaging/flavorgen/cloudprovider/cloud-controller-manager.go
  packaging/flavorgen/cloudprovider/csi/kustomization.yaml
  packaging/flavorgen/flavors/env/envsubts_consts.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-topology.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-vsphere/v1.7/base/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere/v1.7/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere/v1.7/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere/v1.8/base/cluster-template-topology.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3204 🌱 [release-1.9] fix v1.8 clusterctl upgrade e2e tests
  test/e2e/data/infrastructure-vsphere/v1.8/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere/v1.8/topology/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3207 🌱 pr-verify: use env var for passing the PR title
  .github/workflows/pr-verify.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes
