Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2025-03, with the labels that each got.

#3368 [release-1.12] 🌱 Makefile: drop test file to ignore ssh vulnerability in test code
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3367 ✨ Implement CRD migration & bump CAPI to c9261b079e0b
  Makefile
  config/rbac/role.yaml
  controllers/vmware/serviceaccount_controller.go
  go.mod
  go.sum
  main.go
  packaging/go.mod
  packaging/go.sum
  pkg/manager/manager.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_suite_test.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#3380 🌱 vspheremachinetemplate: don't reconcile if className is not set
  controllers/vmware/vspheremachinetemplate_controller.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3386 🌱 Align CRD migration flag to core CAPI
  main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3387 🌱 Log version directly on controller startup
  main.go
  test/extension/main.go
  test/infrastructure/net-operator/main.go
  test/infrastructure/vcsim/main.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3389 🌱 Bump Kubernetes version used for testing to v1.33.0-beta.0
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3392 🌱 Bump CAPI to main (12th March, ccaea78cdbf0)
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/extension/config/tilt/extensionconfig.yaml
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes

#3393 🌱 controllers: fix vspherecluster test flake on vspherecluster deletion
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3395 🌱 Bump CPI to v1.33.0-beta.0
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3383 🌱 Add v1beta2 conditions to vSphereCluster, supervisor mode
  apis/vmware/v1beta1/vspherecluster_types.go
  apis/vmware/v1beta1/zz_generated.deepcopy.go
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  controllers/vmware/serviceaccount_controller.go
  controllers/vmware/servicediscovery_controller.go
  controllers/vmware/servicediscovery_controller_intg_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vmware/vspherecluster_reconciler.go
  pkg/context/vmware/cluster_context.go
  pkg/services/network/dummy_provider.go
  pkg/services/network/netop_provider.go
  pkg/services/network/nsxt_provider.go
  pkg/services/network/nsxt_vpc_provider.go
  pkg/services/vmoperator/control_plane_endpoint.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash

#3398 🐛 Avoid redundant reconciles if only generation of Paused condition changed & bump CAPI to main (17th March, 9e7afa749358)
  .golangci.yml
  Makefile
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  controllers/vmware/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  go.mod
  go.sum
  packaging/flavorgen/flavors/crs/cpi.go
  packaging/flavorgen/flavors/crs/csi.go
  packaging/flavorgen/flavors/crs/util.go
  packaging/flavorgen/flavors/generators.go
  packaging/go.mod
  packaging/go.sum
  pkg/context/cluster_context.go
  pkg/context/machine_context.go
  pkg/context/vm_context.go
  pkg/context/vmware/machine_context.go
  pkg/context/vspheredeploymentzone_context.go
  test/e2e/anti_affinity_test.go
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/ownerrefs_finalizers_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3408 🌱 hack: try to pull from gcr.io/k8s-staging-capi-vsphere/extra/ instead of docker hub
  hack/ci-e2e-lib.sh
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3396 🌱 v1beta2: implement VSphereCluster's Ready, FailureDomainsReady, ClusterModulesReady and VCenterAvailable conditions for govmomi
  .golangci.yml
  apis/v1beta1/vspherecluster_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  controllers/clustermodule_reconciler.go
  controllers/vspherecluster_reconciler.go
  pkg/context/cluster_context.go
  pkg/session/error.go
  pkg/session/session.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3406 🌱 Add v1beta2 conditions to VSphereMachine and VSphereVM
  apis/v1beta1/vspheremachine_types.go
  apis/v1beta1/vspherevm_types.go
  apis/vmware/v1beta1/vspheremachine_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  controllers/vspheremachine_controller.go
  controllers/vspherevm_controller.go
  controllers/vspherevm_ipaddress_reconciler.go
  pkg/context/interfaces.go
  pkg/context/machine_context.go
  pkg/context/vm_context.go
  pkg/context/vmware/machine_context.go
  pkg/services/govmomi/power.go
  pkg/services/govmomi/service.go
  pkg/services/govmomi/util.go
  pkg/services/vimmachine.go
  pkg/services/vmoperator/vmopmachine.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash

#3401 🌱 vspheredeploymentzone/vsphereclusteridentity: implement v1beta2 conditions, govmomi
  apis/v1beta1/vsphereclusteridentity_types.go
  apis/v1beta1/vspheredeploymentzone_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  controllers/vsphereclusteridentity_controller.go
  controllers/vspheredeploymentzone_controller.go
  controllers/vspheredeploymentzone_controller_domain.go
  pkg/context/vspheredeploymentzone_context.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3410 ✨ Improve CRD migration & bump to CAPI release-1.10 (19th March)
  Makefile
  go.mod
  go.sum
  main.go
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3405 🌱 e2e: servicediscovery controller to have an ip to discover in tests
  controllers/vmware/servicediscovery_controller.go
  controllers/vmware/servicediscovery_controller_suite_test.go
  test/framework/vmoperator/vmoperator.go
  test/infrastructure/vcsim/config/rbac/role.yaml
  test/infrastructure/vcsim/controllers/vmip_controller.go
  test/infrastructure/vcsim/controllers/vmoperatordependencies_controller.go
  test/infrastructure/vcsim/main.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash

#3414 🌱 Bump to CAPI v1.10.0-beta.1
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3415 🌱 supervisor: create the VirtualMachineService for the control plane without a name suffix
  pkg/services/vmoperator/control_plane_endpoint.go
  pkg/services/vmoperator/control_plane_endpoint_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, tide/merge-method-squash
