Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2025-02, with the labels that each got.

#3332 :sparkles: Add ability to configure data disk provision type during clone
  apis/v1beta1/types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  docs/proposal/20241003-data-disk-support.md
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  test/e2e/data/infrastructure-vsphere-govmomi/main/multi-disk/data-disks-patch.yaml
  test/e2e/multi_disk_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash, ok-to-test

#3337 🌱 Cleanup copy of CopyAndAmendClusterctlConfig
  test/e2e/e2e_setup_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3338 [release-1.12] 🌱 Bump to Go 1.22.11
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3339 [release-1.11] 🌱 Bump to Go 1.22.11
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3340 [release-1.10] 🌱 Bump to Go 1.22.11
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3329 🌱 Scale test with vcsim
  Makefile
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass-runtimesdk/patch-test-extension.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass-runtimesdk/patch-test-extension.yaml
  test/e2e/e2e_setup_test.go
  test/e2e/scale_test.go
  test/extension/tilt-provider.yaml
  test/framework/vcsim/server.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3342 🌱 Align ginkgo flags to core CAPI
  Makefile
Labels: lgtm, approved, cncf-cla: yes, size/S

#3344 🌱 test: shutdown clustercache when ctx is done
  controllers/controllers_suite_test.go
  controllers/vmware/controllers_suite_test.go
  controllers/vmware/serviceaccount_controller_intg_test.go
  controllers/vmware/serviceaccount_controller_unit_test.go
  controllers/vmware/servicediscovery_controller_intg_test.go
  controllers/vmware/servicediscovery_controller_unit_test.go
  internal/test/helpers/envtest.go
  internal/test/helpers/webhook.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3345 🌱 Bump to Go 1.23.6
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3346 [release-1.12] 🌱 Bump to Go 1.22.12
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3348 [release-1.10] 🌱 Bump to Go 1.22.12
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3347 [release-1.11] 🌱 Bump to Go 1.22.12
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3343 🌱 test: enable upgrades for scale-test and bump CAPI to d5158c2503c84bcf2fc35cf463fca486892b5fae
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/common.go
  test/e2e/config/vsphere.yaml
  test/e2e/dhcp_overrides_test.go
  test/e2e/e2e_setup_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gpu_pci_passthrough_test.go
  test/e2e/hardware_upgrade_test.go
  test/e2e/k8s_conformance_test.go
  test/e2e/multivc_test.go
  test/e2e/scale_test.go
  test/e2e/storage_policy_test.go
  test/framework/framework.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3352 🌱 e2e: fix provisioningMode in tests
  docs/proposal/20241003-data-disk-support.md
  test/e2e/data/infrastructure-vsphere-govmomi/main/multi-disk/data-disks-patch.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3354 🌱 scale: reduce replicas and amount of clusters as we test upgrades too to reduce load
  test/e2e/scale_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3358 🌱 e2e: fixes to node-drain and multidisk e2e test
  Makefile
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  pkg/services/govmomi/vcenter/clone.go
  pkg/services/govmomi/vcenter/clone_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/multi_disk_test.go
  test/e2e/node_drain_test.go
  test/go.mod
  test/go.sum
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3361 🌱 e2e: properly label and cleanup created PVCs during e2e tests in prow
  go.sum
  hack/tools/boskosctl/main.go
  hack/tools/janitor/main.go
  hack/tools/pkg/janitor/janitor.go
  hack/tools/pkg/janitor/janitor_test.go
  hack/tools/pkg/janitor/vsphere.go
  test/e2e/node_drain_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3365 🌱 templates: remove cloud-provider flag for kube-apiserver due to removal in v1.33
  packaging/flavorgen/flavors/generators.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template.yaml
  templates/clusterclass-template-supervisor.yaml
  templates/clusterclass-template.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M
