Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2025-08, with the labels that each got.

#3562 🌱 Bump go-viper/mapstructure to v2.3.0 to fix CVE
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3561 🌱 Update topology api
  internal/apis/topology/v1alpha1/availability_zone.go
  internal/apis/topology/v1alpha1/groupversion_info.go
  internal/apis/topology/v1alpha1/vsphere_zone.go
  internal/apis/topology/v1alpha1/zone.go
  internal/apis/topology/v1alpha1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3565 ✨ Bump to CPI v1.34.0-rc.0
  test/e2e/config/vsphere.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3566 🐛 Fix flake in reconciliation tests
  controllers/vmware/test/controllers_test.go
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3568 🌱 Bump to Go v1.24.6
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3574 🌱 Add retry for govc binary download during tests
  hack/govc-install.sh
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3580 🌱 Update GitHub actions for CAPV v1.15
  .github/workflows/weekly-md-link-check.yaml
  .github/workflows/weekly-security-scan.yaml
  .github/workflows/weekly-test-release.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3582 ✨ Enable KAL in CI
  .github/workflows/pr-golangci-lint.yaml
  .golangci-kal.yml
  Makefile
  hack/tools/.custom-gcl.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M

#3585 🌱 Update InterfaceSpec MTU minimum value
  apis/vmware/v1beta1/vspheremachine_types.go
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, ok-to-test

#3593 🌱 Fix KAL config
  .golangci-kal.yml
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3591 🐛 Remove finalizer from VSphereMachine during deletion if ownerRef was never set
  controllers/vspheremachine_controller.go
  controllers/vspheremachine_controller_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3604 🐛 Bump test module to get latest version of upgrade test
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3600 [release-1.12] 🌱 Bump to github.com/docker/docker v28.0.2+incompatible to fix CVE
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3601 🌱 Temporary fix for ResourceVersion flake
  test/e2e/cluster_upgrade_runtimesdk_test.go
  test/e2e/ownerrefs_finalizers_test.go
Labels: cncf-cla: yes, size/S

#3577 ✨ Bump autoscaler to a9cb59fdd
  test/e2e/data/autoscaler/autoscaler-to-management-workload.yaml
Labels: size/XS, cncf-cla: yes

#3615 🌱 Update OVA list with K8s v1.34 images
  README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes
