Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2025-06, with the labels that each got.

#3483 🐛 govmomi: fix additional printer columns for ControlPlaneEndpoint
  apis/v1alpha3/vspherecluster_types.go
  apis/v1alpha4/vspherecluster_types.go
  apis/v1beta1/vspherecluster_types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3485 🌱 CI: Partially revert 3473 due to having vSphere 8 in community ci
  Makefile
  hack/e2e.sh
  test/e2e/config/vsphere.yaml
  test/infrastructure/vm-operator/config/vm-operator-image-names.yaml
  test/infrastructure/vm-operator/vm-operator-v1.8.6-0-gde75746a.yaml
  test/infrastructure/vm-operator/vm-operator-vc7-compat.diff
Labels: lgtm, approved, cncf-cla: yes, size/M

#3494 🌱 prowjobs: reschedule main periodics at 23 and 1 UTC
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3490 🌱 e2e: also collect pod logs
  hack/e2e.sh
  test/framework/log/collector.go
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3509 🌱 Bump to Go v1.24.4, github.com/cloudflare/circl v1.6.1
  Makefile
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3510 [release-1.13] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1
  Makefile
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, cncf-cla: yes

#3511 [release-1.12] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1
  Makefile
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3512 [release-1.11] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1
  Makefile
  test/go.mod
  test/go.sum
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3517 🌱 hack: debug vsphere connectivity
  hack/e2e.sh
Labels: lgtm, approved, cncf-cla: yes, size/S

#3525 :seedling: e2e: pull calico from a gcr.io mirror
  test/e2e/data/cni/calico/calico.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S, tide/merge-method-squash

#3526 🌱 Bump to CAPI 1.11 version with ref changes
  Makefile
  controllers/vmware/servicediscovery_controller_intg_test.go
  controllers/vmware/test/controllers_test.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vspheredeploymentzone_controller_test.go
  controllers/vspheremachine_controller.go
  controllers/vspheremachine_controller_test.go
  controllers/vspherevm_controller_test.go
  go.mod
  go.sum
  internal/test/helpers/vmware/intg_test_context.go
  packaging/flavorgen/flavors/generators.go
  packaging/go.mod
  packaging/go.sum
  pkg/clustermodule/service_test.go
  pkg/context/fake/fake_cluster_context.go
  pkg/services/network/network_test.go
  pkg/util/machines_test.go
  pkg/util/testutil.go
  templates/cluster-template-external-loadbalancer.yaml
  templates/cluster-template-ignition.yaml
  templates/cluster-template-node-ipam.yaml
  templates/cluster-template-supervisor.yaml
  templates/cluster-template.yaml
  test/e2e/config/vsphere.yaml
  test/framework/log/collector.go
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/controllers/virtualmachine_controller_test.go
  test/infrastructure/vcsim/controllers/vspherevm_controller_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3518 🌱 Enhances VirtualMachineSetResourcePolicy reconcile
  pkg/services/vmoperator/resource_policy.go
  pkg/services/vmoperator/resource_policy_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3531 🌱 fix comment of the NumCoresPerSocket property of VirtualMachineCloneSpec
  apis/v1beta1/types.go
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
Labels: size/XS, lgtm, approved, cncf-cla: yes
