Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2025-05, with the labels that each got.

#3448 🌱 Use release artefacts for CAPI v1.10
  test/e2e/config/vsphere.yaml
Labels: lgtm, approved, cncf-cla: yes, size/S

#3437 📖 Update OVA list with K8s v1.33 images
  README.md
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3434 :seedling: Able to export webhooks for external utilization
  main.go
  webhooks/alias.go
  webhooks/doc.go
  webhooks/vmware/alias.go
  webhooks/vmware/doc.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3459 [release-1.11] 🌱 Bump to Go 1.23.8 to fix CVEs + ignore CVE CVE-2025-22872 via trivy
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  .trivyignore
  Makefile
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspherevm_ipaddress_reconciler.go
  hack/ensure-go.sh
  test/framework/log/collector.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3462 :seedling: Fix web-hook structure names and descriptions
  controllers/vmware/test/controllers_test.go
  internal/test/helpers/envtest.go
  internal/webhooks/vmware/vspheremachine.go
  internal/webhooks/vmware/vspheremachine_test.go
  internal/webhooks/vmware/vspheremachinetemplate.go
  internal/webhooks/vmware/vspheremachinetemplate_test.go
  internal/webhooks/vsphereclustertemplate.go
  internal/webhooks/vspheredeploymentzone.go
  internal/webhooks/vspheredeploymentzone_test.go
  internal/webhooks/vspherefailuredomain.go
  internal/webhooks/vspherefailuredomain_test.go
  internal/webhooks/vspheremachine.go
  internal/webhooks/vspheremachine_test.go
  internal/webhooks/vspheremachinetemplate.go
  internal/webhooks/vspheremachinetemplate_test.go
  internal/webhooks/vspherevm.go
  internal/webhooks/vspherevm_test.go
  main.go
  webhooks/alias.go
  webhooks/vmware/alias.go
Labels: size/L, lgtm, approved, cncf-cla: yes

#3458 [release-1.12] 🌱 Bump to Go 1.23.8 to fix CVEs + ignore CVE CVE-2025-22872 via trivy
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  .trivyignore
  Makefile
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspherevm_ipaddress_reconciler.go
  hack/ensure-go.sh
  test/framework/log/collector.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3464 [release-1.12] 🌱 Bump govulncheck to v1.1.4
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3465 [release-1.11] 🌱 Bump govulncheck to v1.1.4
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3466 [release-1.11] :seedling: Fix web-hook structure names and descriptions
  main.go
  webhooks/alias.go
  webhooks/vmware/alias.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3467 [release-1.12] :seedling: Fix web-hook structure names and descriptions
  main.go
  webhooks/alias.go
  webhooks/vmware/alias.go
Labels: lgtm, approved, cncf-cla: yes, size/M

#3469 🌱 Migrate config and bump golangci lint to v2
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  Makefile
  controllers/vspherecluster_reconciler.go
  controllers/vspherecluster_reconciler_test.go
  controllers/vspheremachine_controller_test.go
  packaging/flavorgen/flavors/clusterclass_generators.go
  pkg/services/govmomi/ipam/status_test.go
  test/e2e/multivc_test.go
  test/e2e/scale_test.go
  test/framework/ip/vcsim.go
Labels: lgtm, approved, cncf-cla: yes, size/XL, tide/merge-method-squash

#3476 🌱 Makefile: Bump Kubebuilder to v1.33
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3473 🌱 Changes for community owned Prow CI
  Makefile
  hack/clean-ci.sh
  hack/e2e.sh
  hack/tools/janitor/main.go
  test/e2e/config/config-overrides-mirror-prow.yaml
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/main/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.11/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.13/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.11/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.13/commons/cluster-network-CIDR.yaml
  test/infrastructure/vm-operator/config/vm-operator-image-names.yaml
  test/infrastructure/vm-operator/vm-operator-v1.8.6-0-gde75746a-65e87004.yaml
  test/infrastructure/vm-operator/vm-operator-vc7-compat.diff
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash
