Repository kubernetes-sigs/cluster-api-provider-vsphere, pull requests merged in 2025-01, with the labels that each got.

#3309 🌱 Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3310 [release-1.11] 🌱 Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3311 [release-1.10] 🌱 Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/M

#3313 🌱 Bump envtest to v1.32.0
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes

#3318 🌱 Bump to controller-runtime v0.19.4
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3320 🌱 Bump the all-go-mod-patch-and-minor group across 2 directories with 5 updates
  Makefile
  go.mod
  go.sum
  hack/govc-install.sh
  packaging/go.mod
  packaging/go.sum
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/controllers/vcsim_controller.go
  test/infrastructure/vcsim/controllers/vcsim_controller_test.go
Labels: size/L, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3321 🌱 Prepare main branch for v1.13 development
  Makefile
  clusterctl-settings.json
  metadata.yaml
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/vsphere.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/clusterclass/clusterclass-quick-start.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/clusterclass/patch-k8s-install-script.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/clusterclass/patch-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/commons/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/commons/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/topology/cluster-template-topology.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/workload/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.12/workload/workload-control-plane-endpoint-ip.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-govmomi/v1.9/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/clusterclass-quick-start-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/patch-k8s-install-script.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/patch-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/patch-prekubeadmscript.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/patch-vm-namingstrategy.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/clusterclass/patch-vsphere-template.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/commons/cluster-network-CIDR.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/commons/cluster-resource-set-label.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/commons/cluster-resource-set.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/topology/cluster-template-topology-supervisor.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/topology/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/workload/kustomization.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.12/workload/workload-control-plane-endpoint-ip.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/clusterclass/patch-controlplaneendpoint.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/v1.9/commons/cluster-resource-set-csi-insecure.yaml
  test/e2e/data/shared/capv/main/metadata.yaml
  test/e2e/data/shared/capv/v1.12/metadata.yaml
  test/extension/tilt-provider.yaml
  test/infrastructure/net-operator/tilt-provider.yaml
  test/infrastructure/vcsim/tilt-provider.yaml
  tilt-provider.yaml
Labels: size/XXL, lgtm, approved, cncf-cla: yes, tide/merge-method-squash

#3323 ⚠️ Bump to CAPI main, CR v0.20, CT v0.17, add PQ fg
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
  config/manager/manager.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
  config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
  controllers/vmware/test/controllers_test.go
  controllers/vspherecluster_reconciler.go
  controllers/vsphereclusteridentity_controller.go
  controllers/vspherevm_ipaddress_reconciler.go
  feature/feature.go
  go.mod
  go.sum
  hack/ensure-go.sh
  internal/test/helpers/envtest.go
  internal/webhooks/vmware/vspheremachine.go
  internal/webhooks/vspheredeploymentzone.go
  internal/webhooks/vspherefailuredomain.go
  internal/webhooks/vspheremachine.go
  internal/webhooks/vspherevm.go
  main.go
  packaging/go.mod
  packaging/go.sum
  test/e2e/config/vsphere.yaml
  test/e2e/data/shared/capi/v1.10/metadata.yaml
  test/framework/log/collector.go
  test/go.mod
  test/go.sum
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_controlplaneendpoints.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vcentersimulators.yaml
  test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vmoperatordependencies.yaml
Labels: lgtm, approved, cncf-cla: yes, size/XL

#3328 🌱 Bump k8s.io/cluster-bootstrap to v0.32.1
  go.mod
  go.sum
  packaging/go.mod
  packaging/go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, approved, cncf-cla: yes, size/S

#3330 [release-1.10] 🌱 Cherry-pick install script from main which does not use apt
  test/e2e/data/infrastructure-vsphere-govmomi/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
  test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
Labels: size/L, lgtm, approved, cncf-cla: yes

#3333 🌱 Bump govulncheck to v1.1.4
  Makefile
Labels: size/XS, lgtm, approved, cncf-cla: yes
